# biopattern-bpfcc
# Autogenerated from man page /usr/share/man/man8/biopattern-bpfcc.8.gz
complete -c biopattern-bpfcc -s h -d 'Show help message and exit'
complete -c biopattern-bpfcc -s d -d 'Trace this disk only'

