# bpftool-gen
# Autogenerated from man page /usr/share/man/man8/bpftool-gen.8.gz
complete -c bpftool-gen -s h -l help -d 'Print short help message (similar to bpftool help)'
complete -c bpftool-gen -s V -l version -d 'Print bpftool\'s version number (similar to bpftool version), the number of th…'
complete -c bpftool-gen -s j -l json -d 'Generate JSON output'
complete -c bpftool-gen -s p -l pretty -d 'Generate human-readable JSON output.  Implies -j'
complete -c bpftool-gen -s d -l debug -d 'Print all logs available, even debug-level information'
complete -c bpftool-gen -s L -l use-loader -d 'For skeletons, generate a "light" skeleton (also known as "loader" skeleton)'

