# btop
# Autogenerated from man page /usr/share/man/man1/btop.1.gz
complete -c btop -s h -l help -d 'show this help message and exit'
complete -c btop -s v -l version -d 'show version info and exit'
complete -c btop -o lc -l low-color -d 'disable truecolor, converts 24-bit colors to 256-color'
complete -c btop -s t -l tty_on -d 'force (ON) tty mode, max 16 colors and tty friendly graph symbols'
complete -c btop -s p -l preset -d 'start with preset, integer value between 0-9'
complete -c btop -l utf-force -d 'force start even if no UTF-8 locale was detected'
complete -c btop -l debug -d 'start in DEBUG mode: shows microsecond timer for information collect and scre…'

