# btrfsck
# Autogenerated from man page /usr/share/man/man8/btrfsck.8.gz
complete -c btrfsck -s b -l backup -d 'use the first valid set of backup roots stored in the superblock'
complete -c btrfsck -l check-data-csum -d 'verify checksums of data blocks'
complete -c btrfsck -l chunk-root -d 'use the given offset bytenr for the chunk tree root'
complete -c btrfsck -s E -l subvol-extents -d 'show extent state for the given subvolume'
complete -c btrfsck -l mode -d 'select mode of operation regarding memory and IO'
complete -c btrfsck -s p -l progress -d 'indicate progress at various checking phases'
complete -c btrfsck -s Q -l qgroup-report -d 'verify qgroup accounting and compare against filesystem accounting'
complete -c btrfsck -s r -l tree-root -d 'use the given offset \'bytenr\' for the tree root'
complete -c btrfsck -l readonly -d '(default) run in read-only mode, this option exists to calm potential panic w…'
complete -c btrfsck -s s -l super -d 'use Nth superblock copy, valid values are 0, 1 or 2 if the respective superbl…'
complete -c btrfsck -l clear-space-cache -d 'completely remove the free space cache of the given version'
complete -c btrfsck -l repair -d 'enable the repair mode and attempt to fix problems where possible'
complete -c btrfsck -l force -d 'warnings in documentation have shown to be insufficient'
complete -c btrfsck -l init-csum-tree -d 'create a new checksum tree and recalculate checksums in all files'
complete -c btrfsck -l init-extent-tree -d 'build the extent tree from scratch'
complete -c btrfsck -l clear-ino-cache -d '(removed: 6. 7)'

