# caddy-trust
# Autogenerated from man page /usr/share/man/man8/caddy-trust.8.gz
complete -c caddy-trust -l adapter -d '	Name of config adapter to apply (if --config is used)'
complete -c caddy-trust -l address -d '	Address of the administration API listener (if --config is not used)'
complete -c caddy-trust -l ca -d '	The ID of the CA to trust (defaults to \'local\')'
complete -c caddy-trust -l config -d '	Configuration file (if --address is not used)'
complete -c caddy-trust -s h -l help -d '	help for trust SEE ALSO'

