# caddy-manpage
# Autogenerated from man page /usr/share/man/man8/caddy-manpage.8.gz
complete -c caddy-manpage -l directory -d '	The output directory where the manpages are generated'
complete -c caddy-manpage -s h -l help -d '	help for manpage SEE ALSO'

