# caddy-start
# Autogenerated from man page /usr/share/man/man8/caddy-start.8.gz
complete -c caddy-start -l adapter -d '	Name of config adapter to apply'
complete -c caddy-start -l config -d '	Configuration file'
complete -c caddy-start -l envfile -d '	Environment file to load'
complete -c caddy-start -s h -l help -d '	help for start'
complete -c caddy-start -l pidfile -d '	Path of file to which to write process ID'
complete -c caddy-start -l watch -d '	Reload changed config file automatically SEE ALSO'

