# caddy-hash-password
# Autogenerated from man page /usr/share/man/man8/caddy-hash-password.8.gz
complete -c caddy-hash-password -l plaintext -d 'Caddy is attached to a controlling tty, the plaintext will not be echoed'
complete -c caddy-hash-password -l algorithm -d 'parameters are used'
complete -c caddy-hash-password -s h -l help -d '	help for hash-password'
complete -c caddy-hash-password -l salt -d '	The password salt SEE ALSO'

