# caddy-run
# Autogenerated from man page /usr/share/man/man8/caddy-run.8.gz
complete -c caddy-run -l adapter -d '	Name of config adapter to apply'
complete -c caddy-run -l config -d '	Configuration file'
complete -c caddy-run -l envfile -d '	Environment file to load'
complete -c caddy-run -l environ -d '	Print environment'
complete -c caddy-run -s h -l help -d '	help for run'
complete -c caddy-run -l pidfile -d '	Path of file to which to write process ID'
complete -c caddy-run -l pingback -d '	Echo confirmation bytes to this address on success'
complete -c caddy-run -l resume -d '	Use saved config, if any (and prefer over --config file)'
complete -c caddy-run -l watch -d '	Watch config file for changes and reload it automatically SEE ALSO'

