# caddy-validate
# Autogenerated from man page /usr/share/man/man8/caddy-validate.8.gz
complete -c caddy-validate -l adapter -d '	Name of config adapter'
complete -c caddy-validate -l config -d '	Input configuration file'
complete -c caddy-validate -s h -l help -d '	help for validate SEE ALSO'

