# caddy-reverse-proxy
# Autogenerated from man page /usr/share/man/man8/caddy-reverse-proxy.8.gz
complete -c caddy-reverse-proxy -l change-host-header -d '	Set upstream Host header to address of upstream'
complete -c caddy-reverse-proxy -l debug -d '	Enable verbose debug logs'
complete -c caddy-reverse-proxy -l from -d '	Address on which to receive traffic'
complete -c caddy-reverse-proxy -s h -l help -d '	help for reverse-proxy'
complete -c caddy-reverse-proxy -l insecure -d '	Disable TLS verification (WARNING: DISABLES SECURITY BY NOT VERIFYING SSL CE…'
complete -c caddy-reverse-proxy -l internal-certs -d '	Use internal CA for issuing certs'
complete -c caddy-reverse-proxy -l to -d '	Upstream address(es) to which traffic should be sent SEE ALSO'

