# caddy-stop
# Autogenerated from man page /usr/share/man/man8/caddy-stop.8.gz
complete -c caddy-stop -l adapter -d '	Name of config adapter to apply (when --config is used)'
complete -c caddy-stop -l address -d '	The address to use to reach the admin API endpoint, if not the default'
complete -c caddy-stop -l config -d '	Configuration file to use to parse the admin address, if --address is not us…'
complete -c caddy-stop -s h -l help -d '	help for stop SEE ALSO'

