# caddy-reload
# Autogenerated from man page /usr/share/man/man8/caddy-reload.8.gz
complete -c caddy-reload -l adapter -d '	Name of config adapter to apply'
complete -c caddy-reload -l address -d '	Address of the administration listener, if different from config'
complete -c caddy-reload -l config -d '	Configuration file (required)'
complete -c caddy-reload -l force -d '	Force config reload, even if it is the same'
complete -c caddy-reload -s h -l help -d '	help for reload SEE ALSO'

