# caddy-fmt
# Autogenerated from man page /usr/share/man/man8/caddy-fmt.8.gz
complete -c caddy-fmt -l diff -d '	Print the differences between the input file and the formatted output'
complete -c caddy-fmt -s h -l help -d '	help for fmt'
complete -c caddy-fmt -l overwrite -d '	Overwrite the input file with the results SEE ALSO'

