# caddy-respond
# Autogenerated from man page /usr/share/man/man8/caddy-respond.8.gz
complete -c caddy-respond -l access-log -d '	Enable the access log'
complete -c caddy-respond -l body -d '	The body of the HTTP response'
complete -c caddy-respond -l debug -d '	Enable more verbose debug-level logging'
complete -c caddy-respond -l header -d '	Set a header on the response (format: "Field: value"'
complete -c caddy-respond -s h -l help -d '	help for respond'
complete -c caddy-respond -l listen -d '	The address to which to bind the listener'
complete -c caddy-respond -l status -d '	The response status code SEE ALSO'

