# caddy-file-server
# Autogenerated from man page /usr/share/man/man8/caddy-file-server.8.gz
complete -c caddy-file-server -l access-log -d '	Enable the access log'
complete -c caddy-file-server -l browse -d '	Enable directory browsing'
complete -c caddy-file-server -l debug -d '	Enable verbose debug logs'
complete -c caddy-file-server -l domain -d '	Domain name at which to serve the files'
complete -c caddy-file-server -s h -l help -d '	help for file-server'
complete -c caddy-file-server -l listen -d '	The address to which to bind the listener'
complete -c caddy-file-server -l root -d '	The path to the root of the site'
complete -c caddy-file-server -l templates -d '	Enable template rendering SEE ALSO'

