# caddy-list-modules
# Autogenerated from man page /usr/share/man/man8/caddy-list-modules.8.gz
complete -c caddy-list-modules -s h -l help -d '	help for list-modules'
complete -c caddy-list-modules -l packages -d '	Print package paths'
complete -c caddy-list-modules -l skip-standard -d '	Skip printing standard modules'
complete -c caddy-list-modules -l versions -d '	Print version information SEE ALSO'

