# caddy-untrust
# Autogenerated from man page /usr/share/man/man8/caddy-untrust.8.gz
complete -c caddy-untrust -l adapter -d '	Name of config adapter to apply (if --config is used)'
complete -c caddy-untrust -l address -d '	Address of the administration API listener (if --config is not used)'
complete -c caddy-untrust -l ca -d '	The ID of the CA to untrust (defaults to \'local\')'
complete -c caddy-untrust -l cert -d '	The path to the CA certificate to untrust'
complete -c caddy-untrust -l config -d '	Configuration file (if --address is not used)'
complete -c caddy-untrust -s h -l help -d '	help for untrust SEE ALSO'

