# caddy-adapt
# Autogenerated from man page /usr/share/man/man8/caddy-adapt.8.gz
complete -c caddy-adapt -l adapter -d '	Name of config adapter'
complete -c caddy-adapt -l config -d '	Configuration file to adapt (required)'
complete -c caddy-adapt -s h -l help -d '	help for adapt'
complete -c caddy-adapt -l pretty -d '	Format the output for human readability'
complete -c caddy-adapt -l validate -d '	Validate the output SEE ALSO'

