# chafa
# Autogenerated from man page /usr/share/man/man1/chafa.1.gz
complete -c chafa -s h -l help
complete -c chafa -l version
complete -c chafa -s f -l format
complete -c chafa -s O -l optimize
complete -c chafa -l relative
complete -c chafa -l passthrough
complete -c chafa -l polite
complete -c chafa -l align
complete -c chafa -s C -l center
complete -c chafa -l clear
complete -c chafa -l exact-size
complete -c chafa -l fit-width
complete -c chafa -l font-ratio
complete -c chafa -l margin-bottom
complete -c chafa -l margin-right
complete -c chafa -l scale
complete -c chafa -s s -l size
complete -c chafa -l stretch
complete -c chafa -l view-size
complete -c chafa -l animate
complete -c chafa -s d -l duration
complete -c chafa -l speed
complete -c chafa -l watch
complete -c chafa -l bg
complete -c chafa -s c -l colors
complete -c chafa -l color-extractor
complete -c chafa -l color-space
complete -c chafa -l dither
complete -c chafa -l dither-grain
complete -c chafa -l dither-intensity
complete -c chafa -l fg
complete -c chafa -l invert
complete -c chafa -s p -l preprocess
complete -c chafa -s t -l threshold
complete -c chafa -l threads
complete -c chafa -s w -l work
complete -c chafa -l fg-only
complete -c chafa -l fill
complete -c chafa -l glyph-file
complete -c chafa -l symbols

