# composer
# Autogenerated from man page /usr/share/man/man1/composer.1.gz
complete -c composer -s h -l help -d 'Display help for the given command'
complete -c composer -s q -l quiet -d 'Do not output any message'
complete -c composer -s V -l version -d 'Display this application version'
complete -c composer -l ansi -l no-ansi -d 'Force (or disable --no-ansi) ANSI output'
complete -c composer -s n -l no-interaction -d 'Do not ask any interactive question'
complete -c composer -l profile -d 'Display timing and memory usage information'
complete -c composer -l no-plugins -d 'Whether to disable plugins'
complete -c composer -l no-scripts -d 'Skips the execution of all scripts defined in composer. json file'
complete -c composer -s d -l working-dir -d 'If specified, use the given directory as working directory'
complete -c composer -l no-cache -d 'Prevent use of the cache'
complete -c composer -s v -l verbose -d 'Increase the verbosity of messages: 1 for normal output, 2 for more verbose o…'

