# dbconfig-generate-include
# Autogenerated from man page /usr/share/man/man1/dbconfig-generate-include.1.gz
complete -c dbconfig-generate-include -s f -l format -d 'use the given output format (default: sh)'
complete -c dbconfig-generate-include -s o -l options -d 'pass options specific to an output format in a semicolon separated list'
complete -c dbconfig-generate-include -s a -l all -d 'include all information in output (default)'
complete -c dbconfig-generate-include -s d -l dbname -d 'include the dbname in the output'
complete -c dbconfig-generate-include -s p -l dbpass -d 'include the dbpass in the output'
complete -c dbconfig-generate-include -s s -l dbserver -d 'include the dbserver in the output'
complete -c dbconfig-generate-include -s P -l dbport -d 'include the dbport in the output'
complete -c dbconfig-generate-include -s u -l dbuser -d 'include the dbuser in the output'
complete -c dbconfig-generate-include -s t -l dbtype -d 'include the dbtype in the output'
complete -c dbconfig-generate-include -s C -l comment -d '"comment out" any unset variables, using a string appropriate comment string …'
complete -c dbconfig-generate-include -s O -l owner -d 'set the owner:group of the output file'
complete -c dbconfig-generate-include -s m -l mode -d 'set the permissions on the output file'
complete -c dbconfig-generate-include -s U -l ucf -d 'register the outputfile with ucf'
complete -c dbconfig-generate-include -s h -l help -d 'display this helpful message'
complete -c dbconfig-generate-include -s v -l version -d 'output the version and exit'

