# dbconfig-load-include
# Autogenerated from man page /usr/share/man/man1/dbconfig-load-include.1.gz
complete -c dbconfig-load-include -s f -l format -d 'use the given output format (default: sh)'
complete -c dbconfig-load-include -s a -l all -d 'include all information in output (default)'
complete -c dbconfig-load-include -s d -l dbname -d 'include the dbname in the output'
complete -c dbconfig-load-include -s p -l dbpass -d 'include the dbpass in the output'
complete -c dbconfig-load-include -s s -l dbserver -d 'include the dbserver in the output'
complete -c dbconfig-load-include -s P -l dbport -d 'include the dbport in the output'
complete -c dbconfig-load-include -s u -l dbuser -d 'include the dbuser in the output'
complete -c dbconfig-load-include -s t -l dbtype -d 'include the dbtype in the output'
complete -c dbconfig-load-include -s h -l help -d 'display this helpful message'
complete -c dbconfig-load-include -s v -l version -d 'output the version and exit  '

