# filegone-bpfcc
# Autogenerated from man page /usr/share/man/man8/filegone-bpfcc.8.gz
complete -c filegone-bpfcc -s h -d 'Print usage message'
complete -c filegone-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel).  EXAMPLES'

