# go-clean
# Autogenerated from man page /usr/share/man/man1/go-clean.1.gz
complete -c go-clean -s i -d 'The -i flag causes clean to remove the corresponding installed archive or bin…'
complete -c go-clean -s n -d 'The -n flag causes clean to print the remove commands it would execute, but n…'
complete -c go-clean -s r -d 'The -r flag causes clean to be applied recursively to all the dependencies of…'
complete -c go-clean -s x -d 'The -x flag causes clean to print remove commands as it executes them'
complete -c go-clean -o cache -d 'The -cache flag causes clean to remove the entire go build cache'
complete -c go-clean -o testcache -d 'The -testcache flag causes clean to expire all test results in the go build c…'
complete -c go-clean -o modcache -d 'The -modcache flag causes clean to remove the entire module download cache, i…'
complete -c go-clean -o fuzzcache -d 'The -fuzzcache flag causes clean to remove files stored in the Go build cache…'

