# go-env
# Autogenerated from man page /usr/share/man/man1/go-env.1.gz
complete -c go-env -o json -d 'prints the environment in JSON format instead of as a shell script'
complete -c go-env -s u -d 'requires one or more arguments and unsets the default setting for the named e…'
complete -c go-env -s w -d 'requires one or more arguments of the form NAME=VALUE and changes the default…'

