# go-fmt
# Autogenerated from man page /usr/share/man/man1/go-fmt.1.gz
complete -c go-fmt -s n -d 'The -n flag prints commands that would be executed'
complete -c go-fmt -s x -d 'The -x flag prints commands as they are executed'
complete -c go-fmt -o mod -d 'The -mod flag\'s value sets which module download mode to use: readonly or ven…'

