# go-gopath-get
# Autogenerated from man page /usr/share/man/man1/go-gopath-get.1.gz
complete -c go-gopath-get -s d -d 'The -d flag instructs get to stop after downloading the packages; that is, it…'
complete -c go-gopath-get -s f -d 'The -f flag, valid only when -u is set, forces get -u not to verify that each…'
complete -c go-gopath-get -o fix -d 'The -fix flag instructs get to run the fix tool on the downloaded packages be…'
complete -c go-gopath-get -s t -d 'The -t flag instructs get to also download the packages required to build the…'
complete -c go-gopath-get -s u -d 'The -u flag instructs get to use the network to update the named packages and…'
complete -c go-gopath-get -s v -d 'The -v flag enables verbose progress and debug output'

