# go-get
# Autogenerated from man page /usr/share/man/man1/go-get.1.gz
complete -c go-get -s t -d 'The -t flag instructs get to consider modules needed to build tests of packag…'
complete -c go-get -s u -d 'The -u flag instructs get to update modules providing dependencies of package…'
complete -c go-get -s x -d 'The -x flag prints commands as they are executed'

