# go-list
# Autogenerated from man page /usr/share/man/man1/go-list.1.gz
complete -c go-list -s f -d 'The -f flag specifies an alternate format for the list, using the syntax of p…'
complete -c go-list -o json -d 'The -json flag causes the package data to be printed in JSON format instead o…'
complete -c go-list -o compiled -d 'The -compiled flag causes list to set CompiledGoFiles to the Go source files …'
complete -c go-list -o deps -d 'The -deps flag causes list to iterate over not just the named packages but al…'
complete -c go-list -s e -d 'The -e flag changes the handling of erroneous packages, those that cannot be …'
complete -c go-list -o export -d 'The -export flag causes list to set the Export field to the name of a file co…'
complete -c go-list -o find -d 'The -find flag causes list to identify the named packages but not resolve the…'
complete -c go-list -o test -d 'The -test flag causes list to report not only the named packages but also the…'
complete -c go-list -s m -d 'The -m flag causes list to list modules instead of packages'
complete -c go-list -s u -d 'The -u flag adds information about available upgrades'
complete -c go-list -o versions -d 'The -versions flag causes list to set the Module\'s Versions field to a list o…'
complete -c go-list -o retracted -d 'The -retracted flag causes list to report information about retracted module …'

