# go-test
# Autogenerated from man page /usr/share/man/man1/go-test.1.gz
complete -c go-test -o args -d 'Pass the remainder of the command line (everything after -args) to the test b…'
complete -c go-test -s c -d 'Compile the test binary to pkg'
complete -c go-test -o exec -d 'Run the test binary using xprog.  The behavior is the same as in \'go run\''
complete -c go-test -s i -d 'Install packages that are dependencies of the test.  Do not run the test'
complete -c go-test -o json -d 'Convert test output to JSON suitable for automated processing'
complete -c go-test -o list -o parallel -o run -o short -o timeout -o failfast -s v -d 'If a run of go test has any test or non-test flags outside this set, the resu…'
complete -c go-test -s o -d 'Compile the test binary to the named file'

