# go-vet
# Autogenerated from man page /usr/share/man/man1/go-vet.1.gz
complete -c go-vet -s n -d 'The -n flag prints commands that would be executed'
complete -c go-vet -s x -d 'The -x flag prints commands as they are executed'
complete -c go-vet -o vettool -d 'The -vettool=prog flag selects a different analysis tool with alternative or …'

