# gofmt
# Autogenerated from man page /usr/share/man/man1/gofmt.1.gz
complete -c gofmt -s d -d 'Do not print reformatted sources to standard output'
complete -c gofmt -s e -d 'Print all (including spurious) errors'
complete -c gofmt -s l -d 'Do not print reformatted sources to standard output'
complete -c gofmt -s r -d 'Apply the rewrite rule to the source before reformatting'
complete -c gofmt -s s -d 'Try to simplify code (after applying the rewrite rule, if any)'
complete -c gofmt -s w -d 'Do not print reformatted sources to standard output'
complete -c gofmt -o cpuprofile -d 'Write cpu profile to the specified file'

