# ibd2sdi
# Autogenerated from man page /usr/share/man/man1/ibd2sdi.1.gz
complete -c ibd2sdi -l help
complete -c ibd2sdi -s h -d 'T{ Command-Line Format T}:T{'
complete -c ibd2sdi -l ------------------------------- -l -------------------------------------- -d 'debug                             (No default value) dump-file               …'
complete -c ibd2sdi -l version
complete -c ibd2sdi -s v -d 'T{ Command-Line Format T}:T{'
complete -c ibd2sdi -l debug
complete -c ibd2sdi -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c ibd2sdi -l dump-file
complete -c ibd2sdi -s d -d 'T{ Command-Line Format T}:T{'
complete -c ibd2sdi -l skip-data
complete -c ibd2sdi -s s -d 'T{ Command-Line Format T}:T{'
complete -c ibd2sdi -l id
complete -c ibd2sdi -s i -d 'T{ Command-Line Format T}:T{'
complete -c ibd2sdi -l type
complete -c ibd2sdi -s t -d 'T{ Command-Line Format T}:T{'
complete -c ibd2sdi -l strict-check
complete -c ibd2sdi -s c -d 'T{ Command-Line Format T}:T{'
complete -c ibd2sdi -l no-check
complete -c ibd2sdi -s n -d 'T{ Command-Line Format T}:T{'
complete -c ibd2sdi -l pretty
complete -c ibd2sdi -s p -d 'T{ Command-Line Format T}:T{'
complete -c ibd2sdi -l skip-pretty -d 'to disable.  ibd2sdi --skip-pretty . /data/test/t1'

