# innochecksum
# Autogenerated from man page /usr/share/man/man1/innochecksum.1.gz
complete -c innochecksum -l help
complete -c innochecksum -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -l info
complete -c innochecksum -s I -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -l version
complete -c innochecksum -s V -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -l verbose
complete -c innochecksum -s v -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -l log -d 'verbose mode, run: innochecksum --verbose To turn off verbose mode, run: inno…'
complete -c innochecksum -l count
complete -c innochecksum -s c -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -l start-page
complete -c innochecksum -s s -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -l end-page
complete -c innochecksum -s e -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -l page
complete -c innochecksum -s p -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -l strict-check
complete -c innochecksum -s C -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -l no-check
complete -c innochecksum -s n -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -l write -d 'option.  If the'
complete -c innochecksum -l allow-mismatches
complete -c innochecksum -s a -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -s w -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -l page-type-summary
complete -c innochecksum -s S -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -l page-type-dump
complete -c innochecksum -s D -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -s l -d 'T{ Command-Line Format T}:T{'
complete -c innochecksum -l debug -d 'option, which was available in earlier releases'

