# jsonlint-php
# Autogenerated from man page /usr/share/man/man1/jsonlint-php.1.gz
complete -c jsonlint-php -s q -l quiet -d 'Cause jsonlint to be quiet when no errors are found'
complete -c jsonlint-php -s h -l help -d 'Show this message'

