# killsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/killsnoop-bpfcc.8.gz
complete -c killsnoop-bpfcc -s h -d 'Print usage message'
complete -c killsnoop-bpfcc -s x -d 'Only print failed kill() syscalls'
complete -c killsnoop-bpfcc -s p -d 'Trace this process ID only which is the sender of signal (filtered in-kernel)'
complete -c killsnoop-bpfcc -s T -d 'Trace this target process ID only which is the receiver of signal (filtered i…'
complete -c killsnoop-bpfcc -s s -d 'Trace this signal only (filtered in-kernel).  EXAMPLES'

