# ksnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/ksnoop-bpfcc.8.gz
complete -c ksnoop-bpfcc -s h -l help -d 'Show help information'
complete -c ksnoop-bpfcc -s V -l version -d 'Show version'
complete -c ksnoop-bpfcc -s d -l debug -d 'Show debug output'
complete -c ksnoop-bpfcc -s p -l pid -d 'Filter events by pid'
complete -c ksnoop-bpfcc -s P -l pages -d 'Specify number of pages used per-CPU for perf event collection'
complete -c ksnoop-bpfcc -s s -l stack -d 'Specified set of functions are traced if and only if they are encountered in …'

