# kvmexit-bpfcc
# Autogenerated from man page /usr/share/man/man8/kvmexit-bpfcc.8.gz
complete -c kvmexit-bpfcc -s h -d 'Print usage message'
complete -c kvmexit-bpfcc -s p -d 'Display process with this PID only, collpase all tids with exit reasons sorte…'
complete -c kvmexit-bpfcc -s v -d 'Display this VCPU only for this PID'
complete -c kvmexit-bpfcc -s a -d 'Display all TIDS for this PID'
complete -c kvmexit-bpfcc -s t -d 'Display thread with this TID only with exit reasons sorted in descending order'
complete -c kvmexit-bpfcc -s T -d 'Display threads for a union like {395490, 395491}'

