# myisamchk
# Autogenerated from man page /usr/share/man/man1/myisamchk.1.gz
complete -c myisamchk -l help
complete -c myisamchk -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l HELP
complete -c myisamchk -s H -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l debug
complete -c myisamchk -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l silent
complete -c myisamchk -s s -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l verbose
complete -c myisamchk -s v -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -s d -d and
complete -c myisamchk -s e
complete -c myisamchk -o vvv -d 'oc o 2. 3'
complete -c myisamchk -l version
complete -c myisamchk -s V -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l wait
complete -c myisamchk -s w -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l var_name -d 'syntax: T{ Variable T}:T{ Default Value T} T{ decode_bits T}:T{ 9 T} T{ ft_ma…'
complete -c myisamchk -l recover -d 'sort_buffer_size is a deprecated synonym for myisam_sort_buffer_size'
complete -c myisamchk -l extend-check -d 'or when the keys are repaired by inserting keys row by row into the table (li…'
complete -c myisamchk -l safe-recover -d 'oc o 2. 3'
complete -c myisamchk -l sort-recover -d option
complete -c myisamchk -l analyze -d 'option is given.  It acts like the myisam_stats_method system variable'
complete -c myisamchk -l check
complete -c myisamchk -s c -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l check-only-changed
complete -c myisamchk -s C -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l fast
complete -c myisamchk -s F -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l force
complete -c myisamchk -s f -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -s r -d 'option.  oc o 2. 3'
complete -c myisamchk -l information
complete -c myisamchk -s i -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l medium-check
complete -c myisamchk -s m -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l read-only
complete -c myisamchk -s T -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l update-state
complete -c myisamchk -s U -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l backup
complete -c myisamchk -s B -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l character-sets-dir -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l correct-checksum -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l data-file-length
complete -c myisamchk -s D -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l keys-used
complete -c myisamchk -s k -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l max-record-length -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l parallel-recover
complete -c myisamchk -s p -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -s n -d 'This is beta-quality code.  Use at your own risk! oc o 2. 3'
complete -c myisamchk -l quick
complete -c myisamchk -s q -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -s o -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l set-collation -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l tmpdir
complete -c myisamchk -s t -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l unpack
complete -c myisamchk -s u -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -s a -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l block-search
complete -c myisamchk -s b -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l description
complete -c myisamchk -l set-auto-increment
complete -c myisamchk -s A -d 'Force AUTO_INCREMENT numbering for new records to start at the given value (o…'
complete -c myisamchk -l sort-index
complete -c myisamchk -s S -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -l sort-records
complete -c myisamchk -s R -d 'T{ Command-Line Format T}:T{'
complete -c myisamchk -o eis -d 'The tbl_name argument can be either the name of a MyISAM table or the name of…'
complete -c myisamchk -o rw-rw----
complete -c myisamchk -l myisam_sort_buffer_size -d 'is probably enough for most cases'
complete -c myisamchk -l 'quick;' -d 'This space must be available on the same file system as the original data fil…'

