# myisam_ftdump
# Autogenerated from man page /usr/share/man/man1/myisam_ftdump.1.gz
complete -c myisam_ftdump -l help
complete -c myisam_ftdump -s h
complete -c myisam_ftdump -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c myisam_ftdump -l count
complete -c myisam_ftdump -s c -d 'T{ Command-Line Format T}:T{'
complete -c myisam_ftdump -l dump
complete -c myisam_ftdump -s d -d 'T{ Command-Line Format T}:T{'
complete -c myisam_ftdump -l length
complete -c myisam_ftdump -s l -d 'T{ Command-Line Format T}:T{'
complete -c myisam_ftdump -l stats
complete -c myisam_ftdump -s s -d 'T{ Command-Line Format T}:T{'
complete -c myisam_ftdump -l verbose
complete -c myisam_ftdump -s v -d 'T{ Command-Line Format T}:T{'

