# mysqld_safe
# Autogenerated from man page /usr/share/man/man1/mysqld_safe.1.gz
complete -c mysqld_safe -l mysqld -d or
complete -c mysqld_safe -l mysqld-version -d 'option to mysqld_safe.  You can also use'
complete -c mysqld_safe -l ledir -d 'to indicate the directory where mysqld_safe should look for the server'
complete -c mysqld_safe -l log-error -d 'option: [mysqld] log-error=error'
complete -c mysqld_safe -l help -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l basedir -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l core-file-size -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l datadir -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l mysqld-safe-log-timestamps -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l log_timestamps -d 'for the server).  This is the default.  oc o 2. 3'
complete -c mysqld_safe -l malloc-lib -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l nice -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l open-files-limit -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l pid-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l plugin-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l port -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l skip-kill-mysqld -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l socket -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l syslog
complete -c mysqld_safe -l skip-syslog -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l syslog-tag -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l timezone -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_safe -l user -d 'T{ Command-Line Format T}:T{'

