# mysqlrepair
# Autogenerated from man page /usr/share/man/man1/mysqlrepair.1.gz
complete -c mysqlrepair -l databases -d or
complete -c mysqlrepair -l all-databases -d 'option to process all tables in one or more databases, an invocation of mysql…'
complete -c mysqlrepair -l help
complete -c mysqlrepair -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -s A -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l all-in-1
complete -c mysqlrepair -s 1 -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l analyze
complete -c mysqlrepair -s a -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l auto-repair -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l bind-address -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l character-sets-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l check
complete -c mysqlrepair -s c -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l check-only-changed
complete -c mysqlrepair -s C -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l check-upgrade
complete -c mysqlrepair -s g -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l compress -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l compression-algorithms -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -s B -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l debug
complete -c mysqlrepair -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l debug-check -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l debug-info -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l default-character-set -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l extended
complete -c mysqlrepair -s e -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l default-auth -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l enable-cleartext-plugin -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l fast
complete -c mysqlrepair -s F -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l force
complete -c mysqlrepair -s f -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l get-server-public-key -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqlrepair -l host
complete -c mysqlrepair -s h -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l login-path -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l medium-check
complete -c mysqlrepair -s m -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l optimize
complete -c mysqlrepair -s o -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l password
complete -c mysqlrepair -s p -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqlrepair -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysqlrepair -l skip-password1 -d option
complete -c mysqlrepair -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysqlrepair -l 'password1;' -d 'oc o 2. 3'
complete -c mysqlrepair -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysqlrepair -l pipe
complete -c mysqlrepair -s W -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l plugin-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l port
complete -c mysqlrepair -s P -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l protocol -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l quick
complete -c mysqlrepair -s q -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l repair
complete -c mysqlrepair -s r -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l shared-memory-base-name -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l silent
complete -c mysqlrepair -s s -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l skip-database -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l socket
complete -c mysqlrepair -s S -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l 'ssl*' -d 'Options that begin with'
complete -c mysqlrepair -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqlrepair -l ssl-fips-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqlrepair -l tables -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l tls-ciphersuites -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l tls-version -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l use-frm -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l user
complete -c mysqlrepair -s u -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l verbose
complete -c mysqlrepair -s v -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l version
complete -c mysqlrepair -s V -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l write-binlog -d 'T{ Command-Line Format T}:T{'
complete -c mysqlrepair -l skip-write-binlog -d 'to cause NO_WRITE_TO_BINLOG to be added to the statements so that they are no…'
complete -c mysqlrepair -l zstd-compression-level -d 'T{ Command-Line Format T}:T{'

