# mysqlanalyze
# Autogenerated from man page /usr/share/man/man1/mysqlanalyze.1.gz
complete -c mysqlanalyze -l databases -d or
complete -c mysqlanalyze -l all-databases -d 'option to process all tables in one or more databases, an invocation of mysql…'
complete -c mysqlanalyze -l help
complete -c mysqlanalyze -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -s A -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l all-in-1
complete -c mysqlanalyze -s 1 -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l analyze
complete -c mysqlanalyze -s a -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l auto-repair -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l bind-address -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l character-sets-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l check
complete -c mysqlanalyze -s c -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l check-only-changed
complete -c mysqlanalyze -s C -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l check-upgrade
complete -c mysqlanalyze -s g -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l compress -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l compression-algorithms -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -s B -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l debug
complete -c mysqlanalyze -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l debug-check -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l debug-info -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l default-character-set -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l extended
complete -c mysqlanalyze -s e -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l default-auth -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l enable-cleartext-plugin -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l fast
complete -c mysqlanalyze -s F -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l force
complete -c mysqlanalyze -s f -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l get-server-public-key -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqlanalyze -l host
complete -c mysqlanalyze -s h -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l login-path -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l medium-check
complete -c mysqlanalyze -s m -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l optimize
complete -c mysqlanalyze -s o -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l password
complete -c mysqlanalyze -s p -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqlanalyze -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysqlanalyze -l skip-password1 -d option
complete -c mysqlanalyze -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysqlanalyze -l 'password1;' -d 'oc o 2. 3'
complete -c mysqlanalyze -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysqlanalyze -l pipe
complete -c mysqlanalyze -s W -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l plugin-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l port
complete -c mysqlanalyze -s P -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l protocol -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l quick
complete -c mysqlanalyze -s q -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l repair
complete -c mysqlanalyze -s r -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l shared-memory-base-name -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l silent
complete -c mysqlanalyze -s s -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l skip-database -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l socket
complete -c mysqlanalyze -s S -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l 'ssl*' -d 'Options that begin with'
complete -c mysqlanalyze -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqlanalyze -l ssl-fips-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqlanalyze -l tables -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l tls-ciphersuites -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l tls-version -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l use-frm -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l user
complete -c mysqlanalyze -s u -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l verbose
complete -c mysqlanalyze -s v -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l version
complete -c mysqlanalyze -s V -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l write-binlog -d 'T{ Command-Line Format T}:T{'
complete -c mysqlanalyze -l skip-write-binlog -d 'to cause NO_WRITE_TO_BINLOG to be added to the statements so that they are no…'
complete -c mysqlanalyze -l zstd-compression-level -d 'T{ Command-Line Format T}:T{'

