# mysqlbinlog
# Autogenerated from man page /usr/share/man/man1/mysqlbinlog.1.gz
complete -c mysqlbinlog -l read-from-remote-server -d option
complete -c mysqlbinlog -l host
complete -c mysqlbinlog -l password
complete -c mysqlbinlog -l port
complete -c mysqlbinlog -l protocol
complete -c mysqlbinlog -l socket
complete -c mysqlbinlog -l user
complete -c mysqlbinlog -l verbose -d 'option, mysqlbinlog adds comments stating the compression algorithm used, the…'
complete -c mysqlbinlog -l help
complete -c mysqlbinlog -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l base64-output -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l bind-address -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l binlog-row-event-max-size -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l character-sets-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l compress -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l compression-algorithms -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l connection-server-id -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l stop-never -d 'option is also specified to maintain the connection to the server, mysqlbinlo…'
complete -c mysqlbinlog -l database
complete -c mysqlbinlog -s d -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l binlog-do-db -d 'option for mysqld, but can be used to specify only one database.  If'
complete -c mysqlbinlog -l rewrite-db -d 'option, the'
complete -c mysqlbinlog -l debug
complete -c mysqlbinlog -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l debug-check -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l debug-info -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l default-auth -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l disable-log-bin
complete -c mysqlbinlog -s D -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l to-last-log -d 'option and are sending the output to the same MySQL server'
complete -c mysqlbinlog -l exclude-gtids -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l force-if-open
complete -c mysqlbinlog -s F -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l force-read
complete -c mysqlbinlog -s f -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l get-server-public-key -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqlbinlog -l hexdump
complete -c mysqlbinlog -s H -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -s h -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l idempotent -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l include-gtids -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l local-load
complete -c mysqlbinlog -s l -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l load-data-local-dir -d 'option to mysql when processing the output from mysqlbinlog'
complete -c mysqlbinlog -l login-path -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l offset
complete -c mysqlbinlog -s o -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l open-files-limit -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -s p -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqlbinlog -l plugin-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -s P -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l print-table-metadata -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l raw -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l result-file -d option
complete -c mysqlbinlog -l read-from-remote-source -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l read-from-remote-master -d 'COM_BINLOG_DUMP or COM_BINLOG_DUMP_GTID commands by setting the option value …'
complete -c mysqlbinlog -s R -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -s r -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l require-row-format -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l server-id -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l server-id-bits -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l set-charset -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l shared-memory-base-name -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l short-form
complete -c mysqlbinlog -s s -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l skip-gtids -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -s S -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l 'ssl*' -d 'Options that begin with'
complete -c mysqlbinlog -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqlbinlog -l ssl-fips-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqlbinlog -l start-datetime -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l start-position
complete -c mysqlbinlog -s j -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l stop-datetime -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l stop-never-slave-server-id -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l stop-position -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l tls-ciphersuites -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l tls-version -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -s t -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -s u -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -s v -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l verify-binlog-checksum
complete -c mysqlbinlog -s c -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l version
complete -c mysqlbinlog -s V -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l zstd-compression-level -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l binary-mode -d option
complete -c mysqlbinlog -l all-databases
complete -c mysqlbinlog -l events
complete -c mysqlbinlog -l routines -d 'to back up all data, and'
complete -c mysqlbinlog -l master-data -d 'to include the current binary log coordinates in the dump file'

