# mysqlreport
# Autogenerated from man page /usr/share/man/man1/mysqlreport.1.gz
complete -c mysqlreport -l help -d 'Output help information and exit'
complete -c mysqlreport -l user
complete -c mysqlreport -l password -d 'As of version 2'
complete -c mysqlreport -l host
complete -c mysqlreport -l port
complete -c mysqlreport -l socket
complete -c mysqlreport -l no-mycnf
complete -c mysqlreport -l dtq -d 'Print Distribution of Total Queries (DTQ) report (under Total in Questions re…'
complete -c mysqlreport -l dms -d 'Print Data Manipulation Statements (DMS) report (under DMS in Questions repor…'
complete -c mysqlreport -l com -d 'Print top N number of non-DMS Com_ status values in descending order (after D…'
complete -c mysqlreport -l sas -d 'Print report for Select_ and Sort_ status values (after Questions report)'
complete -c mysqlreport -l tab -d 'Print Threads, Aborted, and Bytes status reports (after Created temp report)'
complete -c mysqlreport -l qcache -d 'Print Query Cache report'
complete -c mysqlreport -l all -d 'Equivalent to "--dtq --dms --com 3 --sas --qcache"'
complete -c mysqlreport -l infile -d 'Instead of getting SHOW STATUS values from MySQL, read values from FILE'
complete -c mysqlreport -l outfile -d 'After printing the report to screen, print the report to FILE too'
complete -c mysqlreport -l email -d 'After printing the report to screen, email the report to ADDRESS'
complete -c mysqlreport -l flush-status -d 'Execute a "FLUSH STATUS;" after generating the reports'

