# mysql_secure_installation
# Autogenerated from man page /usr/share/man/man1/mysql_secure_installation.1.gz
complete -c mysql_secure_installation -l host -d and
complete -c mysql_secure_installation -l port -d 'can be used on the command line and in option files'
complete -c mysql_secure_installation -l help
complete -c mysql_secure_installation -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -s h -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -l password
complete -c mysql_secure_installation -s p -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -s P -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -l protocol -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -l socket
complete -c mysql_secure_installation -s S -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -l 'ssl*' -d 'Options that begin with'
complete -c mysql_secure_installation -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysql_secure_installation -l ssl-fips-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysql_secure_installation -l tls-ciphersuites -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -l tls-version -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -l use-default -d 'T{ Command-Line Format T}:T{'
complete -c mysql_secure_installation -l user
complete -c mysql_secure_installation -s u -d 'T{ Command-Line Format T}:T{'

