# mysql_ssl_rsa_setup
# Autogenerated from man page /usr/share/man/man1/mysql_ssl_rsa_setup.1.gz
complete -c mysql_ssl_rsa_setup -l datadir -d 'to specify where to create the files, and'
complete -c mysql_ssl_rsa_setup -l verbose -d 'to see the openssl commands that mysql_ssl_rsa_setup executes'
complete -c mysql_ssl_rsa_setup -l ssl -d '(possibly along with ssl_cipher)'
complete -c mysql_ssl_rsa_setup -l ssl-ca
complete -c mysql_ssl_rsa_setup -l ssl-cert
complete -c mysql_ssl_rsa_setup -l ssl-key -d 'options at startup to name the ca. pem, server-cert. pem, and server-key'
complete -c mysql_ssl_rsa_setup -l help -d '? T{ Command-Line Format T}:T{'
complete -c mysql_ssl_rsa_setup -l suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysql_ssl_rsa_setup -l uid
complete -c mysql_ssl_rsa_setup -s v -d 'T{ Command-Line Format T}:T{'
complete -c mysql_ssl_rsa_setup -l version
complete -c mysql_ssl_rsa_setup -s V -d 'T{ Command-Line Format T}:T{'

