# mysqlshow
# Autogenerated from man page /usr/share/man/man1/mysqlshow.1.gz
complete -c mysqlshow -l help
complete -c mysqlshow -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l bind-address -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l character-sets-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l compress
complete -c mysqlshow -s C -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l compression-algorithms -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l count -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l debug
complete -c mysqlshow -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l debug-check -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l debug-info -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l default-character-set -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l default-auth -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l enable-cleartext-plugin -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l get-server-public-key -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqlshow -l host
complete -c mysqlshow -s h -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l keys
complete -c mysqlshow -s k -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l login-path -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l password
complete -c mysqlshow -s p -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqlshow -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysqlshow -l skip-password1 -d option
complete -c mysqlshow -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysqlshow -l 'password1;' -d 'oc o 2. 3'
complete -c mysqlshow -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysqlshow -l pipe
complete -c mysqlshow -s W -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l plugin-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l port
complete -c mysqlshow -s P -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l protocol -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l shared-memory-base-name -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l show-table-type
complete -c mysqlshow -s t -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l socket
complete -c mysqlshow -s S -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l 'ssl*' -d 'Options that begin with'
complete -c mysqlshow -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqlshow -l ssl-fips-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqlshow -l status
complete -c mysqlshow -s i -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l tls-ciphersuites -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l tls-version -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l user
complete -c mysqlshow -s u -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l verbose
complete -c mysqlshow -s v -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l version
complete -c mysqlshow -s V -d 'T{ Command-Line Format T}:T{'
complete -c mysqlshow -l zstd-compression-level -d 'T{ Command-Line Format T}:T{'

