# mysqlcheck
# Autogenerated from man page /usr/share/man/man1/mysqlcheck.1.gz
complete -c mysqlcheck -l databases -d or
complete -c mysqlcheck -l all-databases -d 'option to process all tables in one or more databases, an invocation of mysql…'
complete -c mysqlcheck -l help
complete -c mysqlcheck -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -s A -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l all-in-1
complete -c mysqlcheck -s 1 -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l analyze
complete -c mysqlcheck -s a -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l auto-repair -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l bind-address -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l character-sets-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l check
complete -c mysqlcheck -s c -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l check-only-changed
complete -c mysqlcheck -s C -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l check-upgrade
complete -c mysqlcheck -s g -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l compress -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l compression-algorithms -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -s B -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l debug
complete -c mysqlcheck -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l debug-check -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l debug-info -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l default-character-set -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l extended
complete -c mysqlcheck -s e -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l default-auth -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l enable-cleartext-plugin -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l fast
complete -c mysqlcheck -s F -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l force
complete -c mysqlcheck -s f -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l get-server-public-key -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqlcheck -l host
complete -c mysqlcheck -s h -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l login-path -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l medium-check
complete -c mysqlcheck -s m -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l optimize
complete -c mysqlcheck -s o -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l password
complete -c mysqlcheck -s p -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqlcheck -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysqlcheck -l skip-password1 -d option
complete -c mysqlcheck -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysqlcheck -l 'password1;' -d 'oc o 2. 3'
complete -c mysqlcheck -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysqlcheck -l pipe
complete -c mysqlcheck -s W -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l plugin-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l port
complete -c mysqlcheck -s P -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l protocol -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l quick
complete -c mysqlcheck -s q -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l repair
complete -c mysqlcheck -s r -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l shared-memory-base-name -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l silent
complete -c mysqlcheck -s s -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l skip-database -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l socket
complete -c mysqlcheck -s S -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l 'ssl*' -d 'Options that begin with'
complete -c mysqlcheck -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqlcheck -l ssl-fips-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqlcheck -l tables -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l tls-ciphersuites -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l tls-version -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l use-frm -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l user
complete -c mysqlcheck -s u -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l verbose
complete -c mysqlcheck -s v -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l version
complete -c mysqlcheck -s V -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l write-binlog -d 'T{ Command-Line Format T}:T{'
complete -c mysqlcheck -l skip-write-binlog -d 'to cause NO_WRITE_TO_BINLOG to be added to the statements so that they are no…'
complete -c mysqlcheck -l zstd-compression-level -d 'T{ Command-Line Format T}:T{'

