# mysql_upgrade
# Autogenerated from man page /usr/share/man/man1/mysql_upgrade.1.gz
complete -c mysql_upgrade -l protocol -d 'option forces a connection using TCP/IP rather than the Unix socket file'
complete -c mysql_upgrade -l upgrade-system-tables -d 'option, mysql_upgrade processes all tables in all user schemas as necessary'
complete -c mysql_upgrade -l force -d option
complete -c mysql_upgrade -l skip-sys-schema -d 'option, mysql_upgrade installs the sys schema if it is not installed, and upg…'
complete -c mysql_upgrade -l help -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l bind-address -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l character-sets-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l compress
complete -c mysql_upgrade -s C -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l compression-algorithms -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l debug
complete -c mysql_upgrade -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l debug-check -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l debug-info
complete -c mysql_upgrade -s T -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l default-auth -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l default-character-set -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l get-server-public-key -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysql_upgrade -l host
complete -c mysql_upgrade -s h -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l login-path -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l max-allowed-packet -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l net-buffer-length -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l password
complete -c mysql_upgrade -s p -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l skip-password -d 'option.  oc o 2. 3'
complete -c mysql_upgrade -l pipe
complete -c mysql_upgrade -s W -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l plugin-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l port
complete -c mysql_upgrade -s P -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l shared-memory-base-name -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l socket
complete -c mysql_upgrade -s S -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l 'ssl*' -d 'Options that begin with'
complete -c mysql_upgrade -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysql_upgrade -l ssl-fips-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysql_upgrade -l tls-ciphersuites -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l tls-version -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -s s -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l user
complete -c mysql_upgrade -s u -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l verbose -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l version-check
complete -c mysql_upgrade -s k -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l skip-version-check -d 'oc o 2. 3'
complete -c mysql_upgrade -l write-binlog -d 'T{ Command-Line Format T}:T{'
complete -c mysql_upgrade -l zstd-compression-level -d 'T{ Command-Line Format T}:T{'

