# mysql
# Autogenerated from man page /usr/share/man/man1/mysql.1.gz
complete -c mysql -l quick -d option
complete -c mysql -l help
complete -c mysql -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l authentication-oci-client-config-profile -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l auto-rehash -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l disable-auto-rehash -d 'to disable rehashing'
complete -c mysql -l auto-vertical-output -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l batch
complete -c mysql -s B -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l raw -d 'option.  oc o 2. 3'
complete -c mysql -l binary-as-hex -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l skip-binary-as-hex -d 'oc o 2. 3'
complete -c mysql -l binary-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l commands -d ' oc o 2. 3'
complete -c mysql -l bind-address -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l character-sets-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l column-names -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l column-type-info -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l system-command -d 'option is ignored, and has no effect.  This option has no effect when'
complete -c mysql -l comments
complete -c mysql -s c -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l skip-comments -d '(strip comments), enable with'
complete -c mysql -l compress
complete -c mysql -s C -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l compression-algorithms -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l connect-expired-password -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l connect-timeout -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l database
complete -c mysql -s D -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l debug
complete -c mysql -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l debug-check -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l debug-info
complete -c mysql -s T -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l default-auth -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l default-character-set -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l delimiter -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l disable-named-commands -d 'Disable named commands'
complete -c mysql -l dns-srv-name -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l host -d 'option if both are given'
complete -c mysql -l enable-cleartext-plugin -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l execute
complete -c mysql -s e -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l fido-register-factor -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l force
complete -c mysql -s f -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l get-server-public-key -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysql -l histignore -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l syslog -d 'option is given'
complete -c mysql -s h -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l html
complete -c mysql -s H -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l ignore-spaces
complete -c mysql -s i -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l init-command -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l line-numbers -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l skip-line-numbers -d 'oc o 2. 3'
complete -c mysql -l load-data-local-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l local-infile
complete -c mysql -l login-path -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l max-allowed-packet -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l max-join-size -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l safe-updates -d 'oc o 2. 3'
complete -c mysql -l named-commands
complete -c mysql -s G -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l skip-named-commands -d 'to disable named commands.  See the section called “MYSQL CLIENT COMMANDS”'
complete -c mysql -l net-buffer-length -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l network-namespace -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l no-auto-rehash
complete -c mysql -s A -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l skip-auto-rehash
complete -c mysql -l no-beep
complete -c mysql -s b -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l one-database
complete -c mysql -s o -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l pager -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l skip-pager -d 'the section called “MYSQL CLIENT COMMANDS”, discusses output paging further'
complete -c mysql -l password
complete -c mysql -s p -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l skip-password -d 'option.  oc o 2. 3'
complete -c mysql -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysql -l skip-password1 -d option
complete -c mysql -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysql -l 'password1;' -d 'oc o 2. 3'
complete -c mysql -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysql -l pipe
complete -c mysql -s W -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l plugin-authentication-kerberos-client-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l plugin-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l port
complete -c mysql -s P -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l prompt -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l protocol -d 'T{ Command-Line Format T}:T{'
complete -c mysql -s q -d 'T{ Command-Line Format T}:T{'
complete -c mysql -o 9223372036854775808 -d 'BIGINT column, or 19 characters, plus the 4 characters used for padding and c…'
complete -c mysql -s r -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l silent -d 'option is given), special characters are escaped in the output so they can be…'
complete -c mysql -l reconnect -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l skip-reconnect -d 'oc o 2. 3'
complete -c mysql -l i-am-a-dummy
complete -c mysql -s U -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l skip-safe-updates -d 'on the command line to override it'
complete -c mysql -l select-limit -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l shared-memory-base-name -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l show-warnings -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l sigint-ignore -d 'T{ Command-Line Format T}:T{'
complete -c mysql -s s -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l skip-column-names
complete -c mysql -s N -d 'T{ Command-Line Format T}:T{'
complete -c mysql -s L -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l skip-system-command -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l socket
complete -c mysql -s S -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l 'ssl*' -d 'Options that begin with'
complete -c mysql -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysql -l ssl-fips-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysql -s j -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l table
complete -c mysql -s t -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l tee -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l tls-ciphersuites -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l tls-version -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l unbuffered
complete -c mysql -s n -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l user
complete -c mysql -s u -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l verbose
complete -c mysql -s v -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l version
complete -c mysql -s V -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l vertical
complete -c mysql -s E -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l wait
complete -c mysql -s w -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l xml
complete -c mysql -s X -d 'T{ Command-Line Format T}:T{'
complete -c mysql -l zstd-compression-level -d 'T{ Command-Line Format T}:T{'
complete -c mysql -s F -d and

