# mysqldump
# Autogenerated from man page /usr/share/man/man1/mysqldump.1.gz
complete -c mysqldump -l single-transaction -d 'option is not used, PROCESS (as of MySQL 8. 0. 21) if the'
complete -c mysqldump -l no-tablespaces -d 'option is not used, and (as of MySQL 8. 0'
complete -c mysqldump -l result-file -d 'option, which creates the output in ASCII format: mysqldump [options] --resul…'
complete -c mysqldump -l quick -d 'option (or'
complete -c mysqldump -l opt
complete -c mysqldump -l skip-quick
complete -c mysqldump -l skip-opt -d 'option instead of the'
complete -c mysqldump -l extended-insert -d option
complete -c mysqldump -l databases -d or
complete -c mysqldump -l all-databases -d option
complete -c mysqldump -l help -d 'Option Syntax - Alphabetical Summary'
complete -c mysqldump -l bind-address -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l compress
complete -c mysqldump -s C -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l compression-algorithms -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l default-auth -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l enable-cleartext-plugin -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l get-server-public-key -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqldump -l host
complete -c mysqldump -s h -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l login-path -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l password
complete -c mysqldump -s p -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqldump -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysqldump -l skip-password1 -d option
complete -c mysqldump -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysqldump -l 'password1;' -d 'oc o 2. 3'
complete -c mysqldump -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysqldump -l pipe
complete -c mysqldump -s W -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l plugin-authentication-kerberos-client-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l plugin-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l port
complete -c mysqldump -s P -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l protocol -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l socket
complete -c mysqldump -s S -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l 'ssl*' -d 'Options that begin with'
complete -c mysqldump -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqldump -l ssl-fips-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqldump -l tls-ciphersuites -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l tls-version -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l user
complete -c mysqldump -s u -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l zstd-compression-level -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l add-drop-database -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l add-drop-table -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l add-drop-trigger -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l all-tablespaces
complete -c mysqldump -s Y -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l no-create-db
complete -c mysqldump -s n -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l no-create-info
complete -c mysqldump -s t -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -s y -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l replace -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l allow-keywords -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l comments
complete -c mysqldump -s i -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l skip-comments -d 'oc o 2. 3'
complete -c mysqldump -l debug
complete -c mysqldump -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l debug-check -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l debug-info -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l dump-date -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l skip-dump-date -d 'control whether the date is added to the comment.  The default is'
complete -c mysqldump -l force
complete -c mysqldump -s f -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l ignore-error -d 'option is also given to ignore specific errors,'
complete -c mysqldump -l log-error -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l verbose
complete -c mysqldump -s v -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l version
complete -c mysqldump -s V -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l character-sets-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l default-character-set -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l no-set-names
complete -c mysqldump -s N -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l set-charset -d 'setting, the same as specifying'
complete -c mysqldump -l skip-set-charset -d 'oc o 2. 3'
complete -c mysqldump -l apply-replica-statements -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l apply-slave-statements
complete -c mysqldump -l dump-replica -d or
complete -c mysqldump -l dump-slave -d 'option, the options add a STOP REPLICA (or before MySQL 8. 0'
complete -c mysqldump -l delete-source-logs -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l delete-master-logs -d 'PURGE BINARY LOGS statement to the server after performing the dump operation'
complete -c mysqldump -l source-data -d or
complete -c mysqldump -l master-data -d 'oc o 2. 3'
complete -c mysqldump -l include-source-host-port -d 'options can be used in conjunction with'
complete -c mysqldump -l include-master-host-port -d 'SOURCE_HOST | MASTER_HOST and SOURCE_PORT | MASTER_PORT options for the host …'
complete -c mysqldump -l lock-tables
complete -c mysqldump -l lock-all-tables
complete -c mysqldump -l set-gtid-purged -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l compact -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l skip-add-drop-table
complete -c mysqldump -l skip-add-locks
complete -c mysqldump -l skip-disable-keys
complete -c mysqldump -l compatible -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l complete-insert
complete -c mysqldump -s c -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l create-options -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l fields-terminated-by
complete -c mysqldump -l fields-enclosed-by
complete -c mysqldump -l fields-optionally-enclosed-by
complete -c mysqldump -l fields-escaped-by -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l tab -d 'option and have the same meaning as the corresponding FIELDS clauses for LOAD…'
complete -c mysqldump -l hex-blob -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l lines-terminated-by -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l quote-names
complete -c mysqldump -s Q -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l skip-quote-names
complete -c mysqldump -s r -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l show-create-skip-secondary-engine -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -s T -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l fields-xxx -d and
complete -c mysqldump -l tz-utc -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l skip-tz-utc -d 'oc o 2. 3'
complete -c mysqldump -l xml
complete -c mysqldump -s X -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -s A -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l routines -d and
complete -c mysqldump -l events -d 'options for mysqldump and mysqlpump were not required to include stored routi…'
complete -c mysqldump -s B -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l skip-lock-tables -d 'option. ) Note See the'
complete -c mysqldump -s E -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l ignore-table -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l no-data
complete -c mysqldump -s d -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -s R -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l skip-generated-invisible-primary-key -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l tables -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l triggers -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l skip-triggers
complete -c mysqldump -l where
complete -c mysqldump -s w -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l column-statistics -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l disable-keys
complete -c mysqldump -s K -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -s e -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l insert-ignore -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l max-allowed-packet -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l mysqld-long-query-time -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l net-buffer-length -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l network-timeout
complete -c mysqldump -s M -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l skip-network-timeout -d 'oc o 2. 3'
complete -c mysqldump -l add-locks
complete -c mysqldump -s q -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l flush-logs
complete -c mysqldump -s F -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l flush-privileges -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -s x -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -s l -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l no-autocommit -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l order-by-primary -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l shared-memory-base-name -d 'T{ Command-Line Format T}:T{'
complete -c mysqldump -l skip-compact -d form
complete -c mysqldump -l skip -d 'option for each feature'
complete -c mysqldump -l skip-extended-insert

