# mysqloptimize
# Autogenerated from man page /usr/share/man/man1/mysqloptimize.1.gz
complete -c mysqloptimize -l databases -d or
complete -c mysqloptimize -l all-databases -d 'option to process all tables in one or more databases, an invocation of mysql…'
complete -c mysqloptimize -l help
complete -c mysqloptimize -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -s A -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l all-in-1
complete -c mysqloptimize -s 1 -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l analyze
complete -c mysqloptimize -s a -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l auto-repair -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l bind-address -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l character-sets-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l check
complete -c mysqloptimize -s c -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l check-only-changed
complete -c mysqloptimize -s C -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l check-upgrade
complete -c mysqloptimize -s g -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l compress -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l compression-algorithms -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -s B -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l debug
complete -c mysqloptimize -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l debug-check -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l debug-info -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l default-character-set -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l extended
complete -c mysqloptimize -s e -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l default-auth -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l enable-cleartext-plugin -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l fast
complete -c mysqloptimize -s F -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l force
complete -c mysqloptimize -s f -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l get-server-public-key -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqloptimize -l host
complete -c mysqloptimize -s h -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l login-path -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l medium-check
complete -c mysqloptimize -s m -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l optimize
complete -c mysqloptimize -s o -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l password
complete -c mysqloptimize -s p -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqloptimize -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysqloptimize -l skip-password1 -d option
complete -c mysqloptimize -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysqloptimize -l 'password1;' -d 'oc o 2. 3'
complete -c mysqloptimize -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysqloptimize -l pipe
complete -c mysqloptimize -s W -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l plugin-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l port
complete -c mysqloptimize -s P -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l protocol -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l quick
complete -c mysqloptimize -s q -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l repair
complete -c mysqloptimize -s r -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l shared-memory-base-name -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l silent
complete -c mysqloptimize -s s -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l skip-database -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l socket
complete -c mysqloptimize -s S -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l 'ssl*' -d 'Options that begin with'
complete -c mysqloptimize -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqloptimize -l ssl-fips-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqloptimize -l tables -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l tls-ciphersuites -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l tls-version -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l use-frm -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l user
complete -c mysqloptimize -s u -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l verbose
complete -c mysqloptimize -s v -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l version
complete -c mysqloptimize -s V -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l write-binlog -d 'T{ Command-Line Format T}:T{'
complete -c mysqloptimize -l skip-write-binlog -d 'to cause NO_WRITE_TO_BINLOG to be added to the statements so that they are no…'
complete -c mysqloptimize -l zstd-compression-level -d 'T{ Command-Line Format T}:T{'

