# mysqlimport
# Autogenerated from man page /usr/share/man/man1/mysqlimport.1.gz
complete -c mysqlimport -l help
complete -c mysqlimport -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l bind-address -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l character-sets-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l columns
complete -c mysqlimport -s c -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l compress
complete -c mysqlimport -s C -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l compression-algorithms -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l debug
complete -c mysqlimport -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l debug-check -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l debug-info -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l default-character-set -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l default-auth -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l delete
complete -c mysqlimport -s D -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l enable-cleartext-plugin -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l fields-terminated-by
complete -c mysqlimport -l fields-enclosed-by
complete -c mysqlimport -l fields-optionally-enclosed-by
complete -c mysqlimport -l fields-escaped-by -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l force
complete -c mysqlimport -s f -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l get-server-public-key -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqlimport -l host
complete -c mysqlimport -s h -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l ignore
complete -c mysqlimport -s i -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l replace -d 'option.  oc o 2. 3'
complete -c mysqlimport -l ignore-lines -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l lines-terminated-by -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l local
complete -c mysqlimport -s L -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l lock-tables
complete -c mysqlimport -s l -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l login-path -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l low-priority -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l password
complete -c mysqlimport -s p -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqlimport -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysqlimport -l skip-password1 -d option
complete -c mysqlimport -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysqlimport -l 'password1;' -d 'oc o 2. 3'
complete -c mysqlimport -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysqlimport -l pipe
complete -c mysqlimport -s W -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l plugin-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l port
complete -c mysqlimport -s P -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l protocol -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -s r -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l shared-memory-base-name -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l silent
complete -c mysqlimport -s s -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l socket
complete -c mysqlimport -s S -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l 'ssl*' -d 'Options that begin with'
complete -c mysqlimport -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqlimport -l ssl-fips-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqlimport -l tls-ciphersuites -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l tls-version -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l user
complete -c mysqlimport -s u -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l use-threads -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l verbose
complete -c mysqlimport -s v -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l version
complete -c mysqlimport -s V -d 'T{ Command-Line Format T}:T{'
complete -c mysqlimport -l zstd-compression-level -d 'T{ Command-Line Format T}:T{'

