# mysqladmin
# Autogenerated from man page /usr/share/man/man1/mysqladmin.1.gz
complete -c mysqladmin -l skip-grant-tables -d 'option.  No password change is applied'
complete -c mysqladmin -l verbose -d 'option is given, the output is like that of SHOW FULL PROCESSLIST'
complete -c mysqladmin -l help
complete -c mysqladmin -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l bind-address -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l character-sets-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l compress
complete -c mysqladmin -s C -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l compression-algorithms -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l connect-timeout -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l count
complete -c mysqladmin -s c -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l sleep -d 'option is given.  oc o 2. 3'
complete -c mysqladmin -l debug
complete -c mysqladmin -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l debug-check -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l debug-info -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l default-auth -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l default-character-set -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l enable-cleartext-plugin -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l force
complete -c mysqladmin -s f -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l get-server-public-key -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqladmin -l host
complete -c mysqladmin -s h -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l login-path -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l no-beep
complete -c mysqladmin -s b -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l password
complete -c mysqladmin -s p -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqladmin -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysqladmin -l skip-password1 -d option
complete -c mysqladmin -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysqladmin -l 'password1;' -d 'oc o 2. 3'
complete -c mysqladmin -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysqladmin -l pipe
complete -c mysqladmin -s W -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l plugin-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l port
complete -c mysqladmin -s P -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l protocol -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l relative
complete -c mysqladmin -s r -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l shared-memory-base-name -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l show-warnings -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l shutdown-timeout -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l silent
complete -c mysqladmin -s s -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -s i -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l socket
complete -c mysqladmin -s S -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l 'ssl*' -d 'Options that begin with'
complete -c mysqladmin -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqladmin -l ssl-fips-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqladmin -l tls-ciphersuites -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l tls-version -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l user
complete -c mysqladmin -s u -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -s v -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l version
complete -c mysqladmin -s V -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l vertical
complete -c mysqladmin -s E -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l wait
complete -c mysqladmin -s w -d 'T{ Command-Line Format T}:T{'
complete -c mysqladmin -l zstd-compression-level -d 'T{ Command-Line Format T}:T{'

