# mysqldumpslow
# Autogenerated from man page /usr/share/man/man1/mysqldumpslow.1.gz
complete -c mysqldumpslow -s a -d and
complete -c mysqldumpslow -s n -d options
complete -c mysqldumpslow -l help -d 'T{ Command-Line Format T}:T{'
complete -c mysqldumpslow -l debug
complete -c mysqldumpslow -s d -d 'T{ Command-Line Format T}:T{'
complete -c mysqldumpslow -s g -d 'T{ Type T}:T{ String T} Consider only queries that match the (grep-style) pat…'
complete -c mysqldumpslow -s h -d 'T{ Type T}:T{ String T} T{ Default Value T}:T{ * T} Host name of MySQL server…'
complete -c mysqldumpslow -s i -d 'T{ Type T}:T{ String T} Name of server instance (if using mysql'
complete -c mysqldumpslow -s l -d 'Do not subtract lock time from total time.  oc o 2. 3'
complete -c mysqldumpslow -s r -d 'Reverse the sort order.  oc o 2. 3'
complete -c mysqldumpslow -s s -d 'T{ Type T}:T{ String T} T{ Default Value T}:T{ at T} How to sort the output'
complete -c mysqldumpslow -s t -d 'T{ Type T}:T{ Numeric T} Display only the first N queries in the output'
complete -c mysqldumpslow -l verbose
complete -c mysqldumpslow -s v -d 'T{ Command-Line Format T}:T{'

