# mysqld_multi
# Autogenerated from man page /usr/share/man/man1/mysqld_multi.1.gz
complete -c mysqld_multi -l defaults-file -d 'option).  N can be any positive integer'
complete -c mysqld_multi -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_multi -l defaults-extra-file -d 'option, if one is given'
complete -c mysqld_multi -l help -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_multi -l example -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_multi -l log -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_multi -l mysqladmin -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_multi -l mysqld -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_multi -l no-log -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_multi -l password -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_multi -l silent -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_multi -l tcp-ip -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_multi -l user -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_multi -l verbose -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_multi -l version -d 'T{ Command-Line Format T}:T{'
complete -c mysqld_multi -l pid-file -d 'option is very important if you are using mysqld_safe to start mysqld (for ex…'

