# mysqlslap
# Autogenerated from man page /usr/share/man/man1/mysqlslap.1.gz
complete -c mysqlslap -l create -d or
complete -c mysqlslap -l query -d 'enable you to specify a string containing an SQL statement or a file containi…'
complete -c mysqlslap -l delimiter -d 'option to specify a different delimiter, which enables you to specify stateme…'
complete -c mysqlslap -l help
complete -c mysqlslap -s '?' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l auto-generate-sql
complete -c mysqlslap -s a -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l auto-generate-sql-add-autoincrement -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l auto-generate-sql-execute-number -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l auto-generate-sql-guid-primary -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l auto-generate-sql-load-type -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l auto-generate-sql-secondary-indexes -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l auto-generate-sql-unique-query-number -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l auto-generate-sql-unique-write-number -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l auto-generate-sql-write-number -d 'oc o 2. 3'
complete -c mysqlslap -l commit -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l compress
complete -c mysqlslap -s C -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l compression-algorithms -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l concurrency
complete -c mysqlslap -s c -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l create-schema -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l no-drop -d 'option as well.  oc o 2. 3'
complete -c mysqlslap -l csv -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l debug
complete -c mysqlslap -s '#' -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l debug-check -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l debug-info
complete -c mysqlslap -s T -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l default-auth -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l defaults-extra-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l defaults-file -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l defaults-group-suffix -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -s F -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l detach -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l enable-cleartext-plugin -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l engine
complete -c mysqlslap -s e -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l get-server-public-key -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqlslap -l host
complete -c mysqlslap -s h -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l iterations
complete -c mysqlslap -s i -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l login-path -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l no-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l number-char-cols
complete -c mysqlslap -s x -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l number-int-cols
complete -c mysqlslap -s y -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l number-of-queries -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l only-print -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l password
complete -c mysqlslap -s p -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqlslap -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysqlslap -l skip-password1 -d option
complete -c mysqlslap -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysqlslap -l 'password1;' -d 'oc o 2. 3'
complete -c mysqlslap -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysqlslap -l pipe
complete -c mysqlslap -s W -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l plugin-dir -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l port
complete -c mysqlslap -s P -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l post-query -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l post-system -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l pre-query -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l pre-system -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l print-defaults -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l protocol -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -s q -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l shared-memory-base-name -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l silent
complete -c mysqlslap -s s -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l socket
complete -c mysqlslap -s S -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l sql-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l 'ssl*' -d 'Options that begin with'
complete -c mysqlslap -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqlslap -l ssl-fips-mode -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqlslap -l tls-ciphersuites -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l tls-version -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l user
complete -c mysqlslap -s u -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l verbose
complete -c mysqlslap -s v -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l version
complete -c mysqlslap -s V -d 'T{ Command-Line Format T}:T{'
complete -c mysqlslap -l zstd-compression-level -d 'T{ Command-Line Format T}:T{'

