# needrestart
# Autogenerated from man page /usr/share/man/man1/needrestart.1.gz
complete -c needrestart -s v -d 'be more verbose'
complete -c needrestart -s q -d 'be quiet'
complete -c needrestart -s m -d 'set level of technical details'
complete -c needrestart -s n -d 'set default answer to \'no\''
complete -c needrestart -s c -d 'config filename'
complete -c needrestart -s r -d 'set restart mode'
complete -c needrestart -s b -d 'enable batch mode'
complete -c needrestart -s p -d 'nagios plugin mode: makes output and exit codes nagios compatible'
complete -c needrestart -s f -d 'override debconf(7) frontend, sets the DEBIAN_FRONTEND environment variable t…'
complete -c needrestart -s t -d 'When checking running interpreter processes, allow process start times that a…'
complete -c needrestart -s u -d 'use preferred UI package (-u ? shows available packages)'
complete -c needrestart -s k -d 'check for obsolete kernel'
complete -c needrestart -s l -d 'check for obsolete libraries ENVIRONMENT The following environment variables …'

