# nss-pp
# Autogenerated from man page /usr/share/man/man1/nss-pp.1.gz
complete -c nss-pp -s t -d 'specify the input, one of {private-key | public-key | certificate | certifica…'
complete -c nss-pp -s a -d 'Input is in ascii encoded form (RFC1113)'
complete -c nss-pp -s i -d 'Define an input file to use (default is stdin)'
complete -c nss-pp -s o -d 'Define an output file to use (default is stdout)'
complete -c nss-pp -s u -d 'Use UTF-8 (default is to show non-ascii as . )'
complete -c nss-pp -s w -d 'Don\\*(Aqt wrap long output lines'

