# pg_backupcluster
# Autogenerated from man page /usr/share/man/man1/pg_backupcluster.1.gz
complete -c pg_backupcluster -s c -l checkpoint -d 'X Item "-c --checkpoint=spread|fast" Passed to pg_basebackup'
complete -c pg_backupcluster -s k -l keep-on-error -d 'X Item "-k --keep-on-error" Keep faulty backup directory on error'
complete -c pg_backupcluster -s v -l verbose
complete -c pg_backupcluster -l lc-collate -l lc-collate -l data-checksums

