# pg_buildext
# Autogenerated from man page /usr/share/man/man1/pg_buildext.1.gz
complete -c pg_buildext -o cio -d 'X Item "-cio arg"'
complete -c pg_buildext -s s -d 'X Item "-s" . PD Passed to pg_virtualenv when running installcheck'
complete -c pg_buildext -s m

