# pg_ctlcluster
# Autogenerated from man page /usr/share/man/man1/pg_ctlcluster.1.gz
complete -c pg_ctlcluster -s f -l force -d 'X Item "-f|--force" For stop and restart, the "fast" mode is used which rolls…'
complete -c pg_ctlcluster -s m -l mode -d 'X Item "-m|--mode [smart|fast|immediate]" Shutdown mode to use for stop and r…'
complete -c pg_ctlcluster -l foreground -d 'X Item "--foreground" Start postgres in foreground, without daemonizing via p…'
complete -c pg_ctlcluster -l stdlog -d 'X Item "--stdlog" When --foreground is in use, redirect stderr to the standar…'
complete -c pg_ctlcluster -l skip-systemctl-redirect -d 'X Item "--skip-systemctl-redirect" When running as root, pg_ctlcluster redire…'
complete -c pg_ctlcluster -l bindir -d 'X Item "--bindir directory" Path to pg_ctl'
complete -c pg_ctlcluster -s o -l options -d 'X Item "-o|--options option" Pass given option as command line option to the …'

