# pg_conftool
# Autogenerated from man page /usr/share/man/man1/pg_conftool.1.gz
complete -c pg_conftool -s b -l boolean -d 'X Item "-b, --boolean" Format boolean value as on or off (not for "show all")'
complete -c pg_conftool -s s -l short -d 'X Item "-s, --short" Show only the value (instead of key = value pair)'
complete -c pg_conftool -s v -l verbose -d 'X Item "-v, --verbose" Verbose output'
complete -c pg_conftool -l help

