# pg_lsclusters
# Autogenerated from man page /usr/share/man/man1/pg_lsclusters.1.gz
complete -c pg_lsclusters -s h -l no-header -d 'X Item "-h, --no-header" Do not print the column header line'
complete -c pg_lsclusters -s j -l json -d 'X Item "-j, --json" Output information in JSON format.  Needs JSON'
complete -c pg_lsclusters -s s -l start-conf -d 'X Item "-s, --start-conf" Include start. conf information in status column'
complete -c pg_lsclusters -l help

