# pg_restorecluster
# Autogenerated from man page /usr/share/man/man1/pg_restorecluster.1.gz
complete -c pg_restorecluster -s d -l datadir -d 'X Item "-d --datadir DIR" Use DIR as data directory for the restored cluster …'
complete -c pg_restorecluster -s p -l port -d 'X Item "-p --port N" Use port N for restored cluster (default is next free po…'
complete -c pg_restorecluster -s s -l start -d 'X Item "-s --start" Start cluster after restoring (default for restore from d…'
complete -c pg_restorecluster -l archive -d 'X Item "--archive" Configure cluster for recovery from WAL archive'
complete -c pg_restorecluster -l pitr -d 'X Item "--pitr TIMESTAMP"'
complete -c pg_restorecluster -l recovery-target-time -d 'X Item "--recovery-target-time TIMESTAMP" '
complete -c pg_restorecluster -l wal-archive

