# pg_upgradecluster
# Autogenerated from man page /usr/share/man/man1/pg_upgradecluster.1.gz
complete -c pg_upgradecluster -s v -d 'X Item "-v newversion" Set the version to upgrade to (default: latest availab…'
complete -c pg_upgradecluster -l logfile -d 'X Item "--logfile filel" Set a custom log file path for the upgraded database…'
complete -c pg_upgradecluster -l locale -d 'X Item "--locale=locale" Set the default locale for the upgraded database clu…'
complete -c pg_upgradecluster -l lc-collate -d 'X Item "--lc-collate=locale"'
complete -c pg_upgradecluster -l lc-ctype -d 'X Item "--lc-ctype=locale"'
complete -c pg_upgradecluster -l lc-messages -d 'X Item "--lc-messages=locale"'
complete -c pg_upgradecluster -l lc-monetary -d 'X Item "--lc-monetary=locale"'
complete -c pg_upgradecluster -l lc-numeric -d 'X Item "--lc-numeric=locale"'
complete -c pg_upgradecluster -l lc-time -d 'X Item "--lc-time=locale" '
complete -c pg_upgradecluster -s m -l method -d 'X Item "-m, --method=dump|upgrade|link|clone" Specify the upgrade method'
complete -c pg_upgradecluster -s k -l link -d 'X Item "-k, --link" In pg_upgrade mode, use hard links instead of copying fil…'
complete -c pg_upgradecluster -l clone -d 'X Item "--clone" In pg_upgrade mode, use efficient file cloning (also known a…'
complete -c pg_upgradecluster -s j -l jobs -d 'X Item "-j, --jobs" In pg_upgrade mode, number of simultaneous processes to u…'
complete -c pg_upgradecluster -l keep-port -d 'X Item "--keep-port" By default, the old cluster is moved to a new port, and …'
complete -c pg_upgradecluster -l rename -d 'X Item "--rename=new cluster name" Use a different name for the upgraded clus…'
complete -c pg_upgradecluster -l old-bindir -d 'X Item "--old-bindir=directory" Passed to pg_upgrade'
complete -c pg_upgradecluster -l maintenance-db -d 'X Item "--maintenance-db=database" Database to connect to for maintenance que…'
complete -c pg_upgradecluster -l start -d 'X Item "--[no-]start" Start the new database cluster after upgrading'
complete -c pg_upgradecluster -l keep-on-error

