# pg_virtualenv
# Autogenerated from man page /usr/share/man/man1/pg_virtualenv.1.gz
complete -c pg_virtualenv -s a -d 'X Item "-a" Use all PostgreSQL server versions installed'
complete -c pg_virtualenv -s v -d 'X Item "-v version . " Use these versions (space-separated list)'
complete -c pg_virtualenv -s c -d 'X Item "-c pg_createcluster options" Extra options to pass to pg_createcluster'
complete -c pg_virtualenv -s i -d 'X Item "-i initdb options" Extra initdb options to pass to pg_createcluster'
complete -c pg_virtualenv -s o -d 'X Item "-o guc=value" Configuration option to set in the \\f(CW\\*(C`postgresql'
complete -c pg_virtualenv -s p -d 'X Item "-p package" Set extension_destdir and dynamic_library_path in cluster…'
complete -c pg_virtualenv -s s -d 'X Item "-s" Launch a shell inside the virtual environment when command fails'
complete -c pg_virtualenv -s t -d 'X Item "-t" Install clusters in a temporary directory, even when running as r…'
complete -c pg_virtualenv -s h

