# pktopbm
# Autogenerated from man page /usr/share/man/man1/pktopbm.1.gz
complete -c pktopbm -o character -d 'This is the code point (character number) to which the first     specified ou…'
complete -c pktopbm -s x -d 'The width of the image in columns'
complete -c pktopbm -s y -d 'The height of the image in rows'

