# pnmindex
# Autogenerated from man page /usr/share/man/man1/pnmindex.1.gz
complete -c pnmindex -o size -d 'The size of each thumbnail'
complete -c pnmindex -o across -d 'This is the number of thumbnails in each row. sp The value must be at least 1'
complete -c pnmindex -o black -d 'This controls the color of the padding between the images; by default it is w…'
complete -c pnmindex -o title -d 'This specifies a title to be placed at the top of the image'
complete -c pnmindex -o noquant -d 'Disables color quantization'
complete -c pnmindex -o quant -d 'This option has no effect; it explicitly selects the default behavior of quan…'
complete -c pnmindex -o colors -d 'The maximum number of colors allowed in the overall image'

