# pnmpad
# Autogenerated from man page /usr/share/man/man1/pnmpad.1.gz
complete -c pnmpad -o black -d 'This specifies the color of the padding.   color is like the  '
complete -c pnmpad -o mwidth -d 'Specify amount of left and right padding in pixels'
complete -c pnmpad -o mheight -d 'These options determine the vertical padding'
complete -c pnmpad -o promote -d 'This option tells what to do when the -color option specifies a color that ca…'
complete -c pnmpad -o reportonly -d 'This causes pnmpad to write to Standard Output a description of the   padding…'
complete -c pnmpad -o verbose -d 'This causes verbose messages'
complete -c pnmpad -o color
complete -c pnmpad -o detect-background
complete -c pnmpad -o extend-edge
complete -c pnmpad -o white
complete -c pnmpad -o left
complete -c pnmpad -o right
complete -c pnmpad -o width
complete -c pnmpad -o halign
complete -c pnmpad -o top
complete -c pnmpad -o bottom
complete -c pnmpad -o height
complete -c pnmpad -o valign

