# ppchcalls-bpfcc
# Autogenerated from man page /usr/share/man/man8/ppchcalls-bpfcc.8.gz
complete -c ppchcalls-bpfcc -s h -d 'Print usage message'
complete -c ppchcalls-bpfcc -s p -d 'Trace only this process'
complete -c ppchcalls-bpfcc -s t -d 'Trace only this thread'
complete -c ppchcalls-bpfcc -s i -d 'Print the summary at the specified interval (in seconds)'
complete -c ppchcalls-bpfcc -s d -d 'Total duration of trace (in seconds)'
complete -c ppchcalls-bpfcc -s T -d 'Print only this many entries.  Default: 10'
complete -c ppchcalls-bpfcc -s x -d 'Trace only failed hcalls (i. e. , the return value from the hcall was < 0)'
complete -c ppchcalls-bpfcc -s e -d 'Trace only hcalls that failed with that error (e. g.  -e EPERM or -e 1)'
complete -c ppchcalls-bpfcc -s m -d 'Display times in milliseconds.  Default: microseconds'
complete -c ppchcalls-bpfcc -s P -d 'Summarize by process and not by hcall'
complete -c ppchcalls-bpfcc -s l -d 'List the hcalls recognized by the tool (hard-coded list)'
complete -c ppchcalls-bpfcc -l hcall -d 'Trace this hcall only (use option -l to get all recognized hcalls).  EXAMPLES'

