# pro
# Autogenerated from man page /usr/share/man/man1/pro.1.gz
complete -c pro -s h -l help -d 'Show help for pro or for the specified pro command'
complete -c pro -l debug -d 'Redirect all the debugging logs to the console'
complete -c pro -l version -d 'Show the Pro Client version and exit.  COMMANDS'

