# rdmaucma-bpfcc
# Autogenerated from man page /usr/share/man/man8/rdmaucma-bpfcc.8.gz
complete -c rdmaucma-bpfcc -s h -d 'Print usage message'
complete -c rdmaucma-bpfcc -s D -d 'Show debug infomation of bpf text.  SOURCE This is from bcc.  https://github'

