# scandeps.1p
# Autogenerated from man page /usr/share/man/man1/scandeps.1p.gz
complete -c 'scandeps.1p' -s e -l eval -d 'X Item "-e, --eval=STRING" Scan STRING as a string containing perl code'
complete -c 'scandeps.1p' -s c -l compile -d 'X Item "-c, --compile" Compiles the code and inspects its \\f(CW%INC, in addit…'
complete -c 'scandeps.1p' -s x -l execute -d 'X Item "-x, --execute" Executes the code and inspects its \\f(CW%INC, in addit…'
complete -c 'scandeps.1p' -l xargs -d 'X Item "--xargs=STRING" If -x is given, splits the \\f(CW\\*(C`STRING\\*(C\' usin…'
complete -c 'scandeps.1p' -s B -l bundle -d 'X Item "-B, --bundle" Include core modules in the output and the recursive se…'
complete -c 'scandeps.1p' -s R -l no-recurse -d 'X Item "-R, --no-recurse" Only show dependencies found in the files listed an…'
complete -c 'scandeps.1p' -s V -l verbose -d 'X Item "-V, --verbose" Verbose mode: Output all files found during the proces…'
complete -c 'scandeps.1p' -s C -l cachedeps -d 'X Item "-C, --cachedeps=CACHEFILE" Use CACHEFILE to speed up the scanning pro…'
complete -c 'scandeps.1p' -s T -l modtree

