# sos-upload
# Autogenerated from man page /usr/share/man/man1/sos-upload.1.gz
complete -c sos-upload -l case-id -d 'Specify a case identifier to associate with the archive'
complete -c sos-upload -l upload-url -d 'If a vendor does not provide a default upload location, or if you would like …'
complete -c sos-upload -l upload-user -d 'If a vendor does not provide a default user for uploading, specify the userna…'
complete -c sos-upload -l upload-pass -d 'Specify the password to use for authentication with the destination server'
complete -c sos-upload -l upload-directory -d 'Specify a directory to upload to, if one is not specified by a vendor default…'
complete -c sos-upload -l upload-method -d 'Specify the HTTP method to use for uploading to the provided --upload-url'
complete -c sos-upload -l upload-no-ssl-verify -d 'Disable SSL verification for HTTPS uploads'
complete -c sos-upload -l upload-protocol -d 'Manually specify the protocol to use for uploading to the target upload-url'
complete -c sos-upload -l upload-target -d 'Manually specify the upload target to use for uploading'
complete -c sos-upload -l -upload-s3-endpoint -d 'Endpoint to upload to for S3 bucket'
complete -c sos-upload -l -upload-s3-region -d 'Region to upload to for S3 bucket'
complete -c sos-upload -l -upload-s3-bucket -d 'Name of the S3 bucket to upload to'
complete -c sos-upload -l -upload-s3-access-key -d 'Access key for the S3 bucket'
complete -c sos-upload -l upload-s3-secret-key -d 'Secret key for the S3 bucket'
complete -c sos-upload -l upload-s3-object-prefix -d 'Prefix for the S3 object/key'

