# sslsniff-bpfcc
# Autogenerated from man page /usr/share/man/man8/sslsniff-bpfcc.8.gz
complete -c sslsniff-bpfcc -s h -d 'Print usage message'
complete -c sslsniff-bpfcc -s p -d 'Trace only functions in this process PID'
complete -c sslsniff-bpfcc -s u -d 'Trace only calls made by this UID'
complete -c sslsniff-bpfcc -s x -d 'Show extra fields: UID and TID'
complete -c sslsniff-bpfcc -s c -d 'Show only processes that match this COMM exactly'
complete -c sslsniff-bpfcc -s o -l no-openssl -d 'Do not trace OpenSSL functions'
complete -c sslsniff-bpfcc -s g -l no-gnutls -d 'Do not trace GnuTLS functions'
complete -c sslsniff-bpfcc -s n -l no-nss -d 'Do not trace GnuTLS functions'
complete -c sslsniff-bpfcc -l hexdump -d 'Show data as hexdump instead of trying to decode it as UTF-8'
complete -c sslsniff-bpfcc -l max-buffer-size -d 'Sets maximum buffer size of intercepted data'
complete -c sslsniff-bpfcc -s l -l latency -d 'Show function latency in ms'
complete -c sslsniff-bpfcc -l handshake -d 'Show handshake latency, enabled only if latency option is on'
complete -c sslsniff-bpfcc -l extra-lib -d 'Consist type of the library and library path separated by colon'

