# tcpcong-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcpcong-bpfcc.8.gz
complete -c tcpcong-bpfcc -s h -d 'Print usage message'
complete -c tcpcong-bpfcc -s T -d 'Include a timestamp column'
complete -c tcpcong-bpfcc -s L -d 'Specify local tcp port range'
complete -c tcpcong-bpfcc -s R -d 'Specify remote tcp port range'
complete -c tcpcong-bpfcc -s u -d 'Output in microseconds'
complete -c tcpcong-bpfcc -s d -d 'Show congestion status duration distribution as histograms.  EXAMPLES'

