# tcpconnlat-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcpconnlat-bpfcc.8.gz
complete -c tcpconnlat-bpfcc -s h -d 'Print usage message'
complete -c tcpconnlat-bpfcc -s t -d 'Include a timestamp column'
complete -c tcpconnlat-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c tcpconnlat-bpfcc -s L -d 'Include a LPORT column'
complete -c tcpconnlat-bpfcc -s 4 -d 'Trace IPv4 family only'
complete -c tcpconnlat-bpfcc -s 6 -d 'Trace IPv6 family only'
complete -c tcpconnlat-bpfcc -s v -d 'Print the resulting BPF program, for debugging purposes'

