# tcpdrop-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcpdrop-bpfcc.8.gz
complete -c tcpdrop-bpfcc -s 4 -d 'Trace IPv4 family only'
complete -c tcpdrop-bpfcc -s 6 -d 'Trace IPv6 family only'
complete -c tcpdrop-bpfcc -s h -d 'Print usage message.  EXAMPLES'

