# tcpsynbl-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcpsynbl-bpfcc.8.gz
complete -c tcpsynbl-bpfcc -s h -d 'Print usage message'
complete -c tcpsynbl-bpfcc -s 4 -d 'Trace IPv4 family only'
complete -c tcpsynbl-bpfcc -s 6 -d 'Trace IPv6 family only.  EXAMPLES'

