# trace-cmd-agent
# Autogenerated from man page /usr/share/man/man1/trace-cmd-agent.1.gz
complete -c trace-cmd-agent -s N -d 'Listen over TCP instead of a vsocket'
complete -c trace-cmd-agent -s p -d 'This option will specify the port to listen to'
complete -c trace-cmd-agent -s D -d 'This options causes trace-cmd agent to go into a daemon mode and run in the b…'
complete -c trace-cmd-agent -s P -d 'Allow an agent to also act as a proxy server, where it can be run on a host a…'
complete -c trace-cmd-agent -l verbose -d 'Set the log level'

