# trace-cmd-extract
# Autogenerated from man page /usr/share/man/man1/trace-cmd-extract.1.gz
complete -c trace-cmd-extract -s p -d 'Although extract does not start any traces, some of the plugins require just …'
complete -c trace-cmd-extract -s O -d 'If a latency tracer is being extracted, and the -p option is used, then there…'
complete -c trace-cmd-extract -s o -d 'By default, the extract command will create a trace. dat file'
complete -c trace-cmd-extract -s s -d 'Extract from the snapshot buffer (if the kernel supports it)'
complete -c trace-cmd-extract -l date -d 'This is the same as the trace-cmd-record(1) --date option, but it does cause …'
complete -c trace-cmd-extract -s B -d 'If the kernel supports multiple buffers, this will extract the trace for only…'
complete -c trace-cmd-extract -s a -d 'Extract all existing buffer instances'
complete -c trace-cmd-extract -s t -d 'Extracts the top level instance buffer'
complete -c trace-cmd-extract -l verbose -d 'Set the log level'

