# trace-cmd-split
# Autogenerated from man page /usr/share/man/man1/trace-cmd-split.1.gz
complete -c trace-cmd-split -s i -d 'If this option is not specified, then the split command will look for the fil…'
complete -c trace-cmd-split -s o -d 'By default, the split command will use the input file name as a basis of wher…'
complete -c trace-cmd-split -s s -d 'This specifies how many seconds should be recorded before the new file should…'
complete -c trace-cmd-split -s m -d 'This specifies how many milliseconds should be recorded before the new file s…'
complete -c trace-cmd-split -s u -d 'This specifies how many microseconds should be recorded before the new file s…'
complete -c trace-cmd-split -s e -d 'This specifies how many events should be recorded before the new file should …'
complete -c trace-cmd-split -s p -d 'This specifies the number of pages that should be recorded before the new fil…'
complete -c trace-cmd-split -s r -d 'This option causes the break up to repeat until end-time is reached (or end o…'
complete -c trace-cmd-split -s c -d 'This option causes the above break up to be per CPU. sp . if n \\{\\'
complete -c trace-cmd-split -s C -d 'This option will split for a single CPU'

