# trace-cmd-stop
# Autogenerated from man page /usr/share/man/man1/trace-cmd-stop.1.gz
complete -c trace-cmd-stop -s B -d 'If the kernel supports multiple buffers, this will stop the trace for only th…'
complete -c trace-cmd-stop -s a -d 'Stop the trace for all existing buffer instances'
complete -c trace-cmd-stop -s t -d 'Stops the top level instance buffer'

