# trace-cmd-snapshot
# Autogenerated from man page /usr/share/man/man1/trace-cmd-snapshot.1.gz
complete -c trace-cmd-snapshot -s s -d 'Take a snapshot of the currently running buffer'
complete -c trace-cmd-snapshot -s r -d 'Clear out the buffer'
complete -c trace-cmd-snapshot -s f -d 'Free the snapshot buffer.  The buffer takes up memory inside the kernel'
complete -c trace-cmd-snapshot -s c -d 'Operate on a per cpu snapshot (may not be fully supported by all kernels)'
complete -c trace-cmd-snapshot -s B -d 'If a buffer instance was created, then the -B option will operate on the snap…'

