# trace-cmd-stat
# Autogenerated from man page /usr/share/man/man1/trace-cmd-stat.1.gz
complete -c trace-cmd-stat -s B -d 'Display the status of a given buffer instance'
complete -c trace-cmd-stat -s t -d 'If -B is also specified, show the status of the top level tracing directory a…'
complete -c trace-cmd-stat -s o -d 'Display the all the options along with their values'

