# trace-cmd-restore
# Autogenerated from man page /usr/share/man/man1/trace-cmd-restore.1.gz
complete -c trace-cmd-restore -s c -d 'Create a partial trace'
complete -c trace-cmd-restore -s t -d 'Used with -c, it overrides the location to read the events from'
complete -c trace-cmd-restore -s k -d 'Used with -c, it overrides where to read the kallsyms file from'
complete -c trace-cmd-restore -s o -d 'By default, trace-cmd restore will create a trace. dat file (or trace-partial'
complete -c trace-cmd-restore -s i -d 'By default, trace-cmd restore will read the information of the current system…'

