# trace-cmd-listen
# Autogenerated from man page /usr/share/man/man1/trace-cmd-listen.1.gz
complete -c trace-cmd-listen -s p -d 'This option will specify the port to listen to'
complete -c trace-cmd-listen -s D -d 'This options causes trace-cmd listen to go into a daemon mode and run in the …'
complete -c trace-cmd-listen -s V -d 'Listen on a vsocket instead'
complete -c trace-cmd-listen -s d -d 'This option specifies a directory to write the data files into'
complete -c trace-cmd-listen -s o -d 'This option overrides the default trace in the trace. HOST:PORT'
complete -c trace-cmd-listen -s l -d 'This option writes the output messages to a log file instead of standard outp…'
complete -c trace-cmd-listen -l verbose -d 'Set the log level'

