# trace-cmd-check-events
# Autogenerated from man page /usr/share/man/man1/trace-cmd-check-events.1.gz
complete -c trace-cmd-check-events -l verbose -d 'Set the log level'
complete -c trace-cmd-check-events -s N

