# trace-cmd-profile
# Autogenerated from man page /usr/share/man/man1/trace-cmd-profile.1.gz
complete -c trace-cmd-profile -s p -d 'Set a tracer plugin to run instead of function graph tracing set to depth of 1'
complete -c trace-cmd-profile -s S -d 'Only enable the tracer or events speficied on the command line'
complete -c trace-cmd-profile -s G -d 'Set interrupt (soft and hard) events as global (associated to CPU instead of …'
complete -c trace-cmd-profile -s o -d 'Write the output of the profile to file.  This supersedes --stderr'
complete -c trace-cmd-profile -s H -d 'Add custom event matching to connect any two events together'
complete -c trace-cmd-profile -l stderr -d 'Redirect the output to stderr'
complete -c trace-cmd-profile -l verbose -d 'Set the log level'
complete -c trace-cmd-profile -l - -d 'The above uses -F to follow the sleep task'
complete -c trace-cmd-profile -s l -s l -d 'To disable function graph tracing totally, use:'

