# trace-cmd-hist
# Autogenerated from man page /usr/share/man/man1/trace-cmd-hist.1.gz
complete -c trace-cmd-hist -s i -d 'By default, trace-cmd hist will read the file trace. dat'
complete -c trace-cmd-hist -s P -d 'To compact all events and show the call graphs by ignoring tasks and differen…'

