# trace-cmd-show
# Autogenerated from man page /usr/share/man/man1/trace-cmd-show.1.gz
complete -c trace-cmd-show -s p -d 'Instead of displaying the contents of the "trace" file, use the "trace_pipe" …'
complete -c trace-cmd-show -s s -d 'Instead of reading the "trace" file, read the snapshot file'
complete -c trace-cmd-show -s c -d 'Read only the trace file for a specified CPU'
complete -c trace-cmd-show -s f -d 'Display the full path name of the file that is being displayed'
complete -c trace-cmd-show -s B -d 'If a buffer instance was created, then the -B option will access the files as…'
complete -c trace-cmd-show -l tracing_on -d 'Show if tracing is on for the given instance'
complete -c trace-cmd-show -l current_tracer -d 'Show what the current tracer is'
complete -c trace-cmd-show -l buffer_size -d 'Show the current buffer size (per-cpu)'
complete -c trace-cmd-show -l buffer_total_size -d 'Show the total size of all buffers'
complete -c trace-cmd-show -l ftrace_filter -d 'Show what function filters are set'
complete -c trace-cmd-show -l ftrace_notrace -d 'Show what function disabled filters are set'
complete -c trace-cmd-show -l ftrace_pid -d 'Show the PIDs the function tracer is limited to (if any)'
complete -c trace-cmd-show -l graph_function -d 'Show the functions that will be graphed'
complete -c trace-cmd-show -l graph_notrace -d 'Show the functions that will not be graphed'
complete -c trace-cmd-show -l cpumask -d 'Show the mask of CPUs that tracing will trace'

