# trace-cmd-list
# Autogenerated from man page /usr/share/man/man1/trace-cmd-list.1.gz
complete -c trace-cmd-list -s e -d 'This option will list the available events that are enabled on the local syst…'
complete -c trace-cmd-list -s F -d 'Used with -e regex to show the fields of the event'
complete -c trace-cmd-list -l full -d 'Used with -F which will show the "print fmt" of the event along with the fiel…'
complete -c trace-cmd-list -s l -d 'Used with -e regex to show those events filters'
complete -c trace-cmd-list -s R -d 'Used with -e regex to show those events triggers'
complete -c trace-cmd-list -s s -d 'This option will list the available event systems'
complete -c trace-cmd-list -s t -d 'This option will list the available tracers that are enabled on the local sys…'
complete -c trace-cmd-list -s p -d 'Same as -t and only for legacy purposes'
complete -c trace-cmd-list -s o -d 'This option will list the available Ftrace options that are configured on the…'
complete -c trace-cmd-list -s f -d 'This option will list the available filter functions'
complete -c trace-cmd-list -s P -d 'List the plugin files that get loaded on trace-cmd report'
complete -c trace-cmd-list -s O -d 'List plugin options that can be used by trace-cmd report -O option'
complete -c trace-cmd-list -s B -d 'List defined buffer instances (sub buffers)'
complete -c trace-cmd-list -s C -d 'List defined clocks that can be used with trace-cmd record -C'
complete -c trace-cmd-list -s c -d 'List the available trace file compression algorithms'

