# trace-cmd-clear
# Autogenerated from man page /usr/share/man/man1/trace-cmd-clear.1.gz
complete -c trace-cmd-clear -s B -d 'If the kernel supports multiple buffers, this will clear only the given buffer'
complete -c trace-cmd-clear -s a -d 'Clear all existing buffers, including the top level one'

