# trace-cmd-reset
# Autogenerated from man page /usr/share/man/man1/trace-cmd-reset.1.gz
complete -c trace-cmd-reset -s b -d 'When the kernel boots, the Ftrace ring buffer is of a minimal size (3 pages p…'
complete -c trace-cmd-reset -s B -d 'If the kernel supports multiple buffers, this will reset the trace for only t…'
complete -c trace-cmd-reset -s a -d 'Reset the trace for all existing buffer instances'
complete -c trace-cmd-reset -s d -d 'This option deletes the instance buffer(s) specified by the most recently pre…'
complete -c trace-cmd-reset -s t -d 'Resets the top level instance buffer'

