# trace-cmd-attach
# Autogenerated from man page /usr/share/man/man1/trace-cmd-attach.1.gz
complete -c trace-cmd-attach -s c -d 'Specify a the number of CPUS the guest has'
complete -c trace-cmd-attach -s s -d 'A comma separated list of the format offset,scale,frac,timestamp These values…'

