# trace-cmd-convert
# Autogenerated from man page /usr/share/man/man1/trace-cmd-convert.1.gz
complete -c trace-cmd-convert -s i -d 'By default, trace-cmd convert will read the file trace. dat'
complete -c trace-cmd-convert -s o -d 'The name of the output file, this parameter is mandatory'
complete -c trace-cmd-convert -l file-version -d 'Desired version of the output file.  Supported versions are 6 or 7'
complete -c trace-cmd-convert -l compression -d 'Compression of the trace output file, one of these strings can be passed: '
complete -c trace-cmd-convert -l help -d 'Print usage information'

