# ttysnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/ttysnoop-bpfcc.8.gz
complete -c ttysnoop-bpfcc -s C -d 'Don\'t clear the screen'
complete -c ttysnoop-bpfcc -s s -l datasize -d 'Size of the transmitting buffer (default 256)'
complete -c ttysnoop-bpfcc -s c -l datacount -d 'Number of times ttysnop checks for SIZE bytes of data (default 16)'

