# turbostat
# Autogenerated from man page /usr/share/man/man8/turbostat.8.gz
complete -c turbostat -l add
complete -c turbostat -l cpu
complete -c turbostat -l hide
complete -c turbostat -l enable -d 'The column name "all" can be used to enable all disabled-by-default built-in …'
complete -c turbostat -l show
complete -c turbostat -l Dump
complete -c turbostat -l quiet
complete -c turbostat -l interval
complete -c turbostat -l num_iterations
complete -c turbostat -l out -d 'The file is truncated if it already exists, and it is created if it does not …'
complete -c turbostat -l help
complete -c turbostat -l Joules
complete -c turbostat -l list
complete -c turbostat -l Summary
complete -c turbostat -l TCC
complete -c turbostat -l version
complete -c turbostat -o '	0x00000000' -d '0	0x00000c00 1	0x00000800 2	0x00000a00 3	0x00000800 INPUT'

