# ua
# Autogenerated from man page /usr/share/man/man1/ua.1.gz
complete -c ua -s h -l help -d 'Show help for pro or for the specified pro command'
complete -c ua -l debug -d 'Redirect all the debugging logs to the console'
complete -c ua -l version -d 'Show the Pro Client version and exit.  COMMANDS'

