# ubuntu-advantage
# Autogenerated from man page /usr/share/man/man1/ubuntu-advantage.1.gz
complete -c ubuntu-advantage -s h -l help -d 'Show help for pro or for the specified pro command'
complete -c ubuntu-advantage -l debug -d 'Redirect all the debugging logs to the console'
complete -c ubuntu-advantage -l version -d 'Show the Pro Client version and exit.  COMMANDS'

