# usbip
# Autogenerated from man page /usr/share/man/man8/usbip.8.gz
complete -c usbip -l debug -d 'Print debugging information'
complete -c usbip -l log -d 'Log to syslog'
complete -c usbip -l tcp-port -d 'Connect to PORT on remote host (used for attach and list --remote).  COMMANDS'

