# usbipd
# Autogenerated from man page /usr/share/man/man8/usbipd.8.gz
complete -c usbipd -s 4 -l ipv4 -d 'Bind to IPv4.  Default is both'
complete -c usbipd -s 6 -l ipv6 -d 'Bind to IPv6.  Default is both'
complete -c usbipd -s e -l device -d 'Run in device mode'
complete -c usbipd -s D -l daemon -d 'Run as a daemon process'
complete -c usbipd -s d -l debug -d 'Print debugging information'
complete -c usbipd -o PFILE -l pid -d 'Write process id to FILE'
complete -c usbipd -o tPORT -l tcp-port -d 'Listen on TCP/IP port PORT'
complete -c usbipd -s h -l help -d 'Print the program help message and exit'
complete -c usbipd -s v -l version -d 'Show version.  LIMITATIONS'

