# validate-json
# Autogenerated from man page /usr/share/man/man1/validate-json.1.gz
complete -c validate-json -l dump-schema -d 'Output full schema and exit . HP --dump-schema-url Output URL of schema'
complete -c validate-json -l verbose -d 'Show additional output'
complete -c validate-json -l quiet -d 'Suppress all output'
complete -c validate-json -l dump-schema-url
complete -c validate-json -s h -l help -d 'Show this help'

