# virtiostat-bpfcc
# Autogenerated from man page /usr/share/man/man8/virtiostat-bpfcc.8.gz
complete -c virtiostat-bpfcc -s h -d 'Print usage message'
complete -c virtiostat-bpfcc -s T -d 'Include a time column on output (HH:MM:SS)'
complete -c virtiostat-bpfcc -s D -d 'Show debug infomation of bpf text'
complete -c virtiostat-bpfcc -s d -d 'Filter for driver name'
complete -c virtiostat-bpfcc -s n -d 'Filter for device name'

