# x86_energy_perf_policy
# Autogenerated from man page /usr/share/man/man8/x86_energy_perf_policy.8.gz
complete -c x86_energy_perf_policy -s c -l cpu -d 'The CPU-list may be comma-separated CPU numbers, with dash for range or the s…'
complete -c x86_energy_perf_policy -s p -l pkg -d 'The list is a string of individual package numbers separated by commas, and o…'
complete -c x86_energy_perf_policy -s a -l all -d 'the value-string'
complete -c x86_energy_perf_policy -s B -l epb -d 'See value strings in the table above'
complete -c x86_energy_perf_policy -s d -l debug -d 'x86_energy_perf_policy is silent for updates, and verbose for read-only mode'
complete -c x86_energy_perf_policy -s P -l hwp-epp -d 'See value strings in the table above'
complete -c x86_energy_perf_policy -s m -l hwp-min -d 'The "default" is the value found in IA32_HWP_CAPABILITIES. min'
complete -c x86_energy_perf_policy -s M -l hwp-max -d 'The "default" is the value found in IA32_HWP_CAPABILITIES. max'
complete -c x86_energy_perf_policy -s D -l hwp-desired -d 'The "normal" setting is 0, which corresponds to \'full autonomous\' HWP control'
complete -c x86_energy_perf_policy -s w -l hwp-window -d 'in the sliding window that HWP uses to maintain average frequency'
complete -c x86_energy_perf_policy -s f -l force
complete -c x86_energy_perf_policy -s U -l hwp-use-pkg -d 'indicates whether the per-CPU MSR_IA32_HWP_REQUEST should be overruled (1) or…'
complete -c x86_energy_perf_policy -s H -l hwp-enable
complete -c x86_energy_perf_policy -s t -l turbo-enable
complete -c x86_energy_perf_policy -s v -l version

